# Notebook to forecast Support tickets

#### Imports & others

In [1]:
import os
import getpass
home_dir = os.path.expanduser("~")
username = getpass.getuser()
print(home_dir)
print(username)

/home/bigdata
catarinap

In [2]:
!uv pip install --target ./mypkg --only-binary :all: "pandas<2.0" prophet==1.2.1

Using CPython 3.11.11 interpreter at: venv/bin/python3
Resolved 19 packages in 3.43s
⠙ Preparing packages... (0/19)
⠙ Preparing packages... (0/19)------------------     0 B/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 3.08 KiB/119.90 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------     0 B/11.56 MiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------     0 B/10.79 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
tqdm                 ------------------------------     0 B/76.54 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
six                  ------------------------------ 3.08 KiB/10.79 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
pyparsing            ------------------------------ 3.08 KiB/119.90 KiB
⠙ Preparing packages... (0/19)------------------ 2.97 KiB/11.56 MiB
cycler               ------------------------------ 8.13 KiB/8.13 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 15.08 KiB/96.82 KiB
pyparsing            ------------------------------ 91.08 KiB/119.90 KiB
python-dateutil      ------------------------------ 3.03 KiB/224.50 KiB
contourpy            ------------------------------ 290.95 KiB/318.60 KiB
pytz                 ------------------------------ 19.08 KiB/498.18 KiB
kiwisolver           ------------------------------ 654.95 KiB/1.37 MiB
holidays             ------------------------------ 23.08 KiB/1.40 MiB
pandas               ------------------------------ 2.96 KiB/11.46 MiB
⠙ Preparing packages... (0/19)----------------- 30.97 KiB/11.56 MiB
cycler               ------------------------------ 8.13 KiB/8.13 KiB
tqdm                 ------------------------------ 3.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 15.08 KiB/96.82 KiB
pyparsing            ------------------------------ 91.08 KiB/119.90 KiB
python-dateutil      ------------------------------ 3.03 KiB/224.50 KiB
contourpy            ------------------------------ 294.95 KiB/318.60 KiB
pytz                 ------------------------------ 19.08 KiB/498.18 KiB
kiwisolver           ------------------------------ 654.95 KiB/1.37 MiB
holidays             ------------------------------ 27.08 KiB/1.40 MiB
pandas               ------------------------------ 2.96 KiB/11.46 MiB
⠙ Preparing packages... (0/19)----------------- 30.97 KiB/11.56 MiB
tqdm                 ------------------------------ 7.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 23.08 KiB/96.82 KiB
pyparsing            ------------------------------ 99.08 KiB/119.90 KiB
python-dateutil      ------------------------------ 3.03 KiB/224.50 KiB
contourpy            ------------------------------ 294.95 KiB/318.60 KiB
pytz                 ------------------------------ 23.08 KiB/498.18 KiB
kiwisolver           ------------------------------ 1.08 MiB/1.37 MiB
holidays             ------------------------------ 27.08 KiB/1.40 MiB
pandas               ------------------------------ 2.96 KiB/11.46 MiB
⠙ Preparing packages... (0/19)----------------- 38.97 KiB/11.56 MiB
tqdm                 ------------------------------ 39.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 75.08 KiB/96.82 KiB
packaging            ------------------------------ 35.08 KiB/97.85 KiB
pyparsing            ------------------------------ 115.08 KiB/119.90 KiB
python-dateutil      ------------------------------ 67.03 KiB/224.50 KiB
contourpy            ------------------------------ 314.95 KiB/318.60 KiB
pytz                 ------------------------------ 35.08 KiB/498.18 KiB
holidays             ------------------------------ 67.08 KiB/1.40 MiB
fonttools            ------------------------------ 54.95 KiB/4.84 MiB
pillow               ------------------------------ 22.96 KiB/7.71 MiB
matplotlib           ------------------------------ 130.95 KiB/8.37 MiB
pandas               ------------------------------ 34.96 KiB/11.46 MiB
prophet              ------------------------------ 1.60 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 2.96 KiB/16.04 MiB
tqdm                 ------------------------------ 47.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 83.08 KiB/96.82 KiB
packaging            ------------------------------ 43.08 KiB/97.85 KiB
pyparsing            ------------------------------ 119.08 KiB/119.90 KiB
python-dateutil      ------------------------------ 119.67 KiB/224.50 KiB
contourpy            ------------------------------ 314.95 KiB/318.60 KiB
pytz                 ------------------------------ 35.08 KiB/498.18 KiB
holidays             ------------------------------ 83.08 KiB/1.40 MiB
fonttools            ------------------------------ 62.95 KiB/4.84 MiB
pillow               ------------------------------ 34.96 KiB/7.71 MiB
matplotlib           ------------------------------ 162.95 KiB/8.37 MiB
pandas               ------------------------------ 74.96 KiB/11.46 MiB
prophet              ------------------------------ 1.60 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 2.96 KiB/16.04 MiB
tqdm                 ------------------------------ 47.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 83.08 KiB/96.82 KiB
packaging            ------------------------------ 43.08 KiB/97.85 KiB
python-dateutil      ------------------------------ 119.67 KiB/224.50 KiB
contourpy            ------------------------------ 318.60 KiB/318.60 KiB
pytz                 ------------------------------ 35.08 KiB/498.18 KiB
holidays             ------------------------------ 103.08 KiB/1.40 MiB
fonttools            ------------------------------ 62.95 KiB/4.84 MiB
pillow               ------------------------------ 34.96 KiB/7.71 MiB
matplotlib           ------------------------------ 202.95 KiB/8.37 MiB
pandas               ------------------------------ 82.96 KiB/11.46 MiB
prophet              ------------------------------ 1.60 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 2.96 KiB/16.04 MiB
tqdm                 ------------------------------ 51.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 87.08 KiB/96.82 KiB
packaging            ------------------------------ 79.08 KiB/97.85 KiB
python-dateutil      ------------------------------ 223.67 KiB/224.50 KiB
pytz                 ------------------------------ 35.08 KiB/498.18 KiB
holidays             ------------------------------ 103.08 KiB/1.40 MiB
fonttools            ------------------------------ 98.95 KiB/4.84 MiB
pillow               ------------------------------ 42.96 KiB/7.71 MiB
matplotlib           ------------------------------ 222.95 KiB/8.37 MiB
pandas               ------------------------------ 94.96 KiB/11.46 MiB
prophet              ------------------------------ 1.64 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 6.96 KiB/16.04 MiB
tqdm                 ------------------------------ 55.09 KiB/76.54 KiB
cmdstanpy            ------------------------------ 95.08 KiB/96.82 KiB
packaging            ------------------------------ 91.08 KiB/97.85 KiB
pytz                 ------------------------------ 39.08 KiB/498.18 KiB
holidays             ------------------------------ 119.08 KiB/1.40 MiB
fonttools            ------------------------------ 110.95 KiB/4.84 MiB
pillow               ------------------------------ 54.96 KiB/7.71 MiB
matplotlib           ------------------------------ 234.95 KiB/8.37 MiB
pandas               ------------------------------ 138.96 KiB/11.46 MiB
prophet              ------------------------------ 1.64 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 10.96 KiB/16.04 MiB
stanio               ------------------------------     0 B/7.88 KiB
tqdm                 ------------------------------ 75.09 KiB/76.54 KiB
packaging            ------------------------------ 95.08 KiB/97.85 KiB
pytz                 ------------------------------ 43.08 KiB/498.18 KiB
holidays             ------------------------------ 127.08 KiB/1.40 MiB
fonttools            ------------------------------ 114.95 KiB/4.84 MiB
pillow               ------------------------------ 62.96 KiB/7.71 MiB
matplotlib           ------------------------------ 362.95 KiB/8.37 MiB
pandas               ------------------------------ 154.96 KiB/11.46 MiB
prophet              ------------------------------ 1.79 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 14.96 KiB/16.04 MiB
stanio               ------------------------------     0 B/7.88 KiB
tqdm                 ------------------------------ 75.09 KiB/76.54 KiB
pytz                 ------------------------------ 43.08 KiB/498.18 KiB
holidays             ------------------------------ 131.08 KiB/1.40 MiB
fonttools            ------------------------------ 114.95 KiB/4.84 MiB
pillow               ------------------------------ 70.96 KiB/7.71 MiB
matplotlib           ------------------------------ 458.95 KiB/8.37 MiB
pandas               ------------------------------ 158.96 KiB/11.46 MiB
prophet              ------------------------------ 1.79 MiB/11.56 MiB
⠙ Preparing packages... (0/19)----------------- 14.96 KiB/16.04 MiB
stanio               ------------------------------     0 B/7.88 KiB
pytz                 ------------------------------ 47.08 KiB/498.18 KiB
holidays             ------------------------------ 139.08 KiB/1.40 MiB
fonttools            ------------------------------ 118.95 KiB/4.84 MiB
pillow               ------------------------------ 111.12 KiB/7.71 MiB
matplotlib           ------------------------------ 490.95 KiB/8.37 MiB
pandas               ------------------------------ 166.96 KiB/11.46 MiB
prophet              ------------------------------ 1.79 MiB/11.56 MiB
⠙ Preparing packages... (0/19)------------------ 18.96 KiB/16.04 MiB
importlib-resources  ------------------------------ 7.05 KiB/36.36 KiB
pytz                 ------------------------------ 91.08 KiB/498.18 KiB
holidays             ------------------------------ 183.08 KiB/1.40 MiB
fonttools            ------------------------------ 582.95 KiB/4.84 MiB
pillow               ------------------------------ 183.12 KiB/7.71 MiB
matplotlib           ------------------------------ 1.12 MiB/8.37 MiB
pandas               ------------------------------ 246.96 KiB/11.46 MiB
prophet              ------------------------------ 2.26 MiB/11.56 MiB
⠙ Preparing packages... (0/19)------------------ 66.96 KiB/16.04 MiB
importlib-resources  ------------------------------ 7.05 KiB/36.36 KiB
pytz                 ------------------------------ 103.08 KiB/498.18 KiB
holidays             ------------------------------ 187.08 KiB/1.40 MiB
fonttools            ------------------------------ 586.95 KiB/4.84 MiB
pillow               ------------------------------ 191.12 KiB/7.71 MiB
matplotlib           ------------------------------ 1.19 MiB/8.37 MiB
pandas               ------------------------------ 286.96 KiB/11.46 MiB
prophet              ------------------------------ 2.26 MiB/11.56 MiB
⠙ Preparing packages... (0/19)------------------ 98.96 KiB/16.04 MiB
pytz                 ------------------------------ 111.08 KiB/498.18 KiB
holidays             ------------------------------ 259.08 KiB/1.40 MiB
fonttools            ------------------------------ 1.14 MiB/4.84 MiB
pillow               ------------------------------ 279.12 KiB/7.71 MiB
matplotlib           ------------------------------ 1.40 MiB/8.37 MiB
pandas               ------------------------------ 486.96 KiB/11.46 MiB
prophet              ------------------------------ 2.47 MiB/11.56 MiB
⠹ Preparing packages... (11/19)----------------- 302.96 KiB/16.04 MiB
pytz                 ------------------------------ 115.08 KiB/498.18 KiB
holidays             ------------------------------ 287.08 KiB/1.40 MiB
fonttools            ------------------------------ 1.37 MiB/4.84 MiB
pillow               ------------------------------ 763.12 KiB/7.71 MiB
matplotlib           ------------------------------ 1.84 MiB/8.37 MiB
pandas               ------------------------------ 490.96 KiB/11.46 MiB
prophet              ------------------------------ 2.48 MiB/11.56 MiB
⠹ Preparing packages... (11/19)----------------- 386.96 KiB/16.04 MiB
pytz                 ------------------------------ 179.08 KiB/498.18 KiB
holidays             ------------------------------ 483.08 KiB/1.40 MiB
fonttools            ------------------------------ 1.72 MiB/4.84 MiB
pillow               ------------------------------ 1.37 MiB/7.71 MiB
matplotlib           ------------------------------ 2.58 MiB/8.37 MiB
pandas               ------------------------------ 762.96 KiB/11.46 MiB
prophet              ------------------------------ 2.92 MiB/11.56 MiB
⠹ Preparing packages... (11/19)----------------- 494.96 KiB/16.04 MiB
pytz                 ------------------------------ 255.08 KiB/498.18 KiB
holidays             ------------------------------ 727.08 KiB/1.40 MiB
fonttools            ------------------------------ 2.17 MiB/4.84 MiB
pillow               ------------------------------ 1.82 MiB/7.71 MiB
matplotlib           ------------------------------ 3.06 MiB/8.37 MiB
pandas               ------------------------------ 1.07 MiB/11.46 MiB
prophet              ------------------------------ 3.37 MiB/11.56 MiB
⠹ Preparing packages... (11/19)----------------- 574.96 KiB/16.04 MiB
pytz                 ------------------------------ 331.08 KiB/498.18 KiB
holidays             ------------------------------ 799.08 KiB/1.40 MiB
fonttools            ------------------------------ 2.69 MiB/4.84 MiB
pillow               ------------------------------ 2.13 MiB/7.71 MiB
matplotlib           ------------------------------ 3.40 MiB/8.37 MiB
pandas               ------------------------------ 1.39 MiB/11.46 MiB
prophet              ------------------------------ 3.78 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 770.96 KiB/16.04 MiB
pytz                 ------------------------------ 403.08 KiB/498.18 KiB
holidays             ------------------------------ 867.08 KiB/1.40 MiB
fonttools            ------------------------------ 3.46 MiB/4.84 MiB
pillow               ------------------------------ 2.82 MiB/7.71 MiB
matplotlib           ------------------------------ 3.88 MiB/8.37 MiB
pandas               ------------------------------ 1.55 MiB/11.46 MiB
prophet              ------------------------------ 4.38 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 938.96 KiB/16.04 MiB
holidays             ------------------------------ 939.08 KiB/1.40 MiB
fonttools            ------------------------------ 3.75 MiB/4.84 MiB
pillow               ------------------------------ 3.32 MiB/7.71 MiB
matplotlib           ------------------------------ 4.25 MiB/8.37 MiB
pandas               ------------------------------ 1.68 MiB/11.46 MiB
prophet              ------------------------------ 4.80 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 1.15 MiB/16.04 MiB
holidays             ------------------------------ 963.08 KiB/1.40 MiB
fonttools            ------------------------------ 3.81 MiB/4.84 MiB
pillow               ------------------------------ 3.49 MiB/7.71 MiB
matplotlib           ------------------------------ 4.34 MiB/8.37 MiB
pandas               ------------------------------ 1.71 MiB/11.46 MiB
prophet              ------------------------------ 4.94 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 1.32 MiB/16.04 MiB
holidays             ------------------------------ 1019.08 KiB/1.40 MiB
fonttools            ------------------------------ 4.08 MiB/4.84 MiB
pillow               ------------------------------ 3.87 MiB/7.71 MiB
matplotlib           ------------------------------ 4.95 MiB/8.37 MiB
pandas               ------------------------------ 1.87 MiB/11.46 MiB
prophet              ------------------------------ 5.67 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 2.51 MiB/16.04 MiB
holidays             ------------------------------ 1.02 MiB/1.40 MiB
fonttools            ------------------------------ 4.75 MiB/4.84 MiB
pillow               ------------------------------ 4.75 MiB/7.71 MiB
matplotlib           ------------------------------ 5.91 MiB/8.37 MiB
pandas               ------------------------------ 1.97 MiB/11.46 MiB
prophet              ------------------------------ 6.80 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 2.76 MiB/16.04 MiB
holidays             ------------------------------ 1.03 MiB/1.40 MiB
pillow               ------------------------------ 5.98 MiB/7.71 MiB
matplotlib           ------------------------------ 6.82 MiB/8.37 MiB
pandas               ------------------------------ 2.00 MiB/11.46 MiB
prophet              ------------------------------ 7.46 MiB/11.56 MiB
⠸ Preparing packages... (11/19)----------------- 3.32 MiB/16.04 MiB
holidays             ------------------------------ 1.03 MiB/1.40 MiB
pillow               ------------------------------ 6.26 MiB/7.71 MiB
matplotlib           ------------------------------ 6.94 MiB/8.37 MiB
pandas               ------------------------------ 2.00 MiB/11.46 MiB
prophet              ------------------------------ 7.67 MiB/11.56 MiB
⠼ Preparing packages... (13/19)----------------- 3.59 MiB/16.04 MiB
holidays             ------------------------------ 1.05 MiB/1.40 MiB

In [3]:
import sys
import os

# 1. Point Python to your custom folder
path = os.path.abspath('./mypkg')
if path not in sys.path:
    sys.path.insert(0, path)

# 2. Verify the folder actually contains prophet
if not os.path.exists(os.path.join(path, "prophet")):
    print(f"ERROR: 'prophet' is not in {path}. The installation likely failed.")
else:
    from prophet import Prophet
    print("Success: Prophet imported from ./mypkg")

[D 2026-05-07 10:56:31,672.672 matplotlib] matplotlib data path: /home/bigdata/mypkg/matplotlib/mpl-data
[D 2026-05-07 10:56:31,680.680 matplotlib] CONFIGDIR=/home/bigdata/.config/matplotlib
[D 2026-05-07 10:56:31,699.699 matplotlib] interactive is False
[D 2026-05-07 10:56:31,699.699 matplotlib] platform is linux
[D 2026-05-07 10:56:31,900.900 matplotlib] CACHEDIR=/home/bigdata/.cache/matplotlib
[D 2026-05-07 10:56:31,900.900 matplotlib.font_manager] font search path [PosixPath('/home/bigdata/mypkg/matplotlib/mpl-data/fonts/ttf'), PosixPath('/home/bigdata/mypkg/matplotlib/mpl-data/fonts/afm'), PosixPath('/home/bigdata/mypkg/matplotlib/mpl-data/fonts/pdfcorefonts')]
[I 2026-05-07 10:56:32,686.686 matplotlib.font_manager] generated new fontManager

Success: Prophet imported from ./mypkg

In [28]:
from prophet import Prophet
import pandas as pd
import numpy as np

In [29]:
import importlib.metadata
print(importlib.metadata.version("prophet"))

1.2.1

In [30]:
!hdfs dfs -ls /user/{username}/notebooks/Workload\ Projections

Found 28 items
drwx------   - catarinap hdfs          0 2026-03-23 11:09 /user/catarinap/notebooks/Workload Projections/.ipynb_checkpoints
-rw-r--r--   3 catarinap hdfs  108114332 2026-03-23 09:49 /user/catarinap/notebooks/Workload Projections/181797_part_aa.csv
-rw-r--r--   3 catarinap hdfs  107778046 2026-03-23 09:48 /user/catarinap/notebooks/Workload Projections/181797_part_ab.csv
-rw-------   3 catarinap hdfs    8334793 2025-09-08 13:16 /user/catarinap/notebooks/Workload Projections/Adyen 2025 Calls.csv
-rw-------   3 catarinap hdfs   13301199 2025-09-12 11:22 /user/catarinap/notebooks/Workload Projections/Aircall_Combined_Detailed.csv
-rw-r--r--   3 catarinap hdfs     177186 2026-03-23 11:07 /user/catarinap/notebooks/Workload Projections/Data Processing.ipynb
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 14:14 /user/catarinap/notebooks/Workload Projections/Forecasted data
-rw-r--r--   3 catarinap hdfs      61456 2026-03-23 11:09 /user/catarinap/notebooks/Workload Projections/Forecasting code.ipynb
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 13:50 /user/catarinap/notebooks/Workload Projections/account_details_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 13:50 /user/catarinap/notebooks/Workload Projections/active_account_summary_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 13:50 /user/catarinap/notebooks/Workload Projections/active_accounts_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 14:12 /user/catarinap/notebooks/Workload Projections/aggregated_cases_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:34 /user/catarinap/notebooks/Workload Projections/aggregated_tickets_df.parquet
-rw-------   3 catarinap hdfs   12575597 2025-06-04 11:21 /user/catarinap/notebooks/Workload Projections/call_history_2023_2025.csv
-rw-------   3 catarinap hdfs   11436096 2025-05-15 11:20 /user/catarinap/notebooks/Workload Projections/call_history_df.csv
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 14:02 /user/catarinap/notebooks/Workload Projections/cases_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-23 11:05 /user/catarinap/notebooks/Workload Projections/clean_calls_df.parquet
-rw-r--r--   3 catarinap hdfs      86845 2025-04-02 15:26 /user/catarinap/notebooks/Workload Projections/example_wp_log_peyton_manning.csv
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:32 /user/catarinap/notebooks/Workload Projections/groups_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:34 /user/catarinap/notebooks/Workload Projections/historical_ticket_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 14:02 /user/catarinap/notebooks/Workload Projections/measures_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:32 /user/catarinap/notebooks/Workload Projections/metrics_df.parquet
-rw-r--r--   3 catarinap hdfs       5511 2025-05-09 15:02 /user/catarinap/notebooks/Workload Projections/non_latam_accounts_forecast.csv
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:32 /user/catarinap/notebooks/Workload Projections/organizations_df.parquet
-rw-r--r--   3 catarinap hdfs   13944276 2025-05-01 14:09 /user/catarinap/notebooks/Workload Projections/prophet_model_test.ipynb
drwxr-xr-x   - catarinap hdfs          0 2026-03-12 13:39 /user/catarinap/notebooks/Workload Projections/queue_mapping_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:31 /user/catarinap/notebooks/Workload Projections/queue_mapping_zendesk_df.parquet
drwxr-xr-x   - catarinap hdfs          0 2026-03-02 15:32 /user/catarinap/notebooks/Workload Projections/tickets_df.parquet

## Read data

In [31]:
!hdfs dfs -copyToLocal /user/{username}/notebooks/Workload\ Projections/aggregated_cases_df.parquet

copyToLocal: `aggregated_cases_df.parquet/_SUCCESS': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00000-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00001-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00002-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00003-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00004-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00005-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00006-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00007-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00008-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00009-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00010-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00011-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00012-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00013-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00014-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00015-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00016-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00017-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00018-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00019-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00020-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00021-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00022-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00023-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00024-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00025-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00026-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00027-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00028-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00029-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00030-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00031-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00032-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00033-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00034-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00035-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00036-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00037-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00038-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00039-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00040-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00041-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00042-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00043-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00044-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00045-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00046-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00047-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00048-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00049-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00050-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00051-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00052-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00053-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00054-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00055-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00056-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00057-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00058-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00059-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00060-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00061-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00062-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00063-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00064-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00065-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00066-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00067-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00068-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00069-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00070-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00071-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00072-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00073-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00074-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00075-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00076-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00077-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00078-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00079-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00080-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00081-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00082-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00083-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00084-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00085-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00086-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00087-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00088-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00089-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00090-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00091-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00092-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00093-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00094-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00095-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00096-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00097-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00098-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00099-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00100-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00101-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00102-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00103-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00104-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00105-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00106-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00107-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00108-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00109-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00110-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00111-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00112-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00113-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00114-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00115-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00116-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00117-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00118-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00119-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00120-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00121-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00122-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00123-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00124-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00125-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00126-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00127-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00128-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00129-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00130-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00131-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00132-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00133-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00134-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00135-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00136-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00137-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00138-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00139-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00140-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00141-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00142-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00143-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00144-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00145-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00146-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00147-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00148-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00149-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00150-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00151-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00152-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00153-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00154-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00155-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00156-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00157-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00158-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00159-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00160-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00161-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists
copyToLocal: `aggregated_cases_df.parquet/part-00162-19791f14-46a8-45a8-ba04-5cb4c2d37cf3-c000.zstd.parquet': File exists

In [32]:
tickets = pd.read_parquet('aggregated_cases_df.parquet').drop_duplicates()
tickets.head()

,month,domain,subdomain,team,support_team,origin,category,unique_id_count
0,2024-02-01,Support,Technical Support,Technical Support,Ecom Cards,Email,Service,864
1,2024-09-01,Support,Operational Support,Operational Support,Operational Support,Email,Internal,990
2,2025-01-01,Support,Technical Support,Account Setup Operations,Account Setup Operations,Webform,Service,394
3,2025-10-01,Support,Technical Support,Technical Support,LATAM - Technical Support,Email,Service,588
4,2025-11-01,Support,Operational Support,Operational Support,Operational Support,Email,Service,4349

In [33]:
tickets.to_csv('tickets.csv', index=False)

In [34]:
!hdfs dfs -put -f tickets.csv /user/{username}/notebooks/adyen_downloader

In [35]:
tickets['support_team'].unique()

array(['Ecom Cards', 'Operational Support', 'Account Setup Operations',
       'LATAM - Technical Support', 'Disputes', None, 'Ecom APM',
       'Finance', 'Japan', 'IPP Core', 'IPP Adv. Payments',
       'India - Technical Support', 'IPP Integrations', 'Partner Support',
       'Ecom Core', 'Platforms', 'Ecom Integration',
       'LATAM - Operational Support', 'China'], dtype=object)

In [36]:
!hdfs dfs -copyToLocal /user/{username}/notebooks/Workload\ Projections/active_account_summary_df.parquet

In [37]:
accounts = pd.read_parquet('active_account_summary_df.parquet')
accounts.head()

    month_seq region managed_region pillar_clean  unique_accounts
0  2013-05-01   EMEA           EMEA      Digital               71
1  2013-11-01   EMEA           None      Digital              383
2  2022-08-01   EMEA           None    Platforms               91
3  2025-06-01   APAC           None      Digital              435
4  2024-08-01   APAC           None         None                4

In [38]:
accounts.to_csv('accounts.csv', index=False)

In [39]:
!hdfs dfs -put -f accounts.csv /user/{username}/notebooks/adyen_downloader

In [40]:
grouped = accounts.groupby('month_seq')['unique_accounts'].sum().reset_index()
print(grouped)

      month_seq  unique_accounts
0    2010-06-01                1
1    2010-07-01                8
2    2010-08-01               14
3    2010-09-01               30
4    2010-10-01               46
..          ...              ...
185  2025-11-01             9676
186  2025-12-01             9728
187  2026-01-01             9750
188  2026-02-01             9788
189  2026-03-01             9798

[190 rows x 2 columns]

In [41]:
!hdfs dfs -copyToLocal /user/{username}/notebooks/Workload\ Projections/clean_calls_df.parquet

copyToLocal: `clean_calls_df.parquet/_SUCCESS': File exists
copyToLocal: `clean_calls_df.parquet/part-00000-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00001-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00002-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00003-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00004-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00005-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00006-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00007-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00008-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00009-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00010-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00011-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00012-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00013-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00014-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00015-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00016-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00017-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00018-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00019-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00020-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00021-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00022-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00023-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00024-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00025-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00026-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00027-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00028-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00029-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00030-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00031-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00032-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00033-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00034-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00035-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00036-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00037-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00038-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00039-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00040-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00041-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00042-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00043-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00044-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00045-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00046-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00047-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00048-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00049-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00050-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00051-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00052-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00053-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00054-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00055-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00056-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00057-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00058-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00059-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00060-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00061-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00062-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00063-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00064-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00065-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00066-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00067-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00068-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00069-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00070-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00071-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00072-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00073-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00074-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00075-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00076-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00077-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00078-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00079-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00080-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00081-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00082-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00083-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00084-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00085-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00086-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00087-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00088-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00089-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00090-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00091-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00092-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00093-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00094-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00095-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00096-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00097-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00098-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00099-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00100-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00101-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00102-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00103-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00104-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00105-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00106-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00107-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00108-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00109-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00110-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00111-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00112-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00113-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00114-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00115-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists
copyToLocal: `clean_calls_df.parquet/part-00116-1050be65-241f-441a-9e14-458358e98323-c000.zstd.parquet': File exists

In [42]:
calls = pd.read_parquet('clean_calls_df.parquet')
calls.head()

        month         support_team  calls
0  2023-01-01                Japan    157
1  2023-01-01                LATAM    100
2  2023-01-01  Operational Support   1137
3  2023-02-01                Japan    167
4  2023-02-01                LATAM    107

In [43]:
calls['month'].unique()

array(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
       '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
       '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
       '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
       '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
       '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01',
       '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
       '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
       '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01',
       '2026-01-01', '2026-02-01', '2026-03-01'], dtype=object)

In [44]:
calls.to_csv('clean_calls_df.csv', index=False)

In [45]:
!hdfs dfs -put -f clean_calls_df.csv /user/{username}/notebooks/adyen_downloader

## Account Growth

In [46]:
!uv pip install --target ./mypkg statsmodels

Resolved 9 packages in 293ms
⠙ Preparing packages... (0/3)
⠙ Preparing packages... (0/3)----     0 B/233.30 kB
⠙ Preparing packages... (0/3)---- 3.64 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 7.74 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 11.83 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 15.93 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 20.02 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 28.21 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 40.50 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 44.60 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 56.89 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 69.17 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 85.50 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 89.66 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 105.97 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 106.04 kB/233.30 kB
⠙ Preparing packages... (0/3)---- 122.36 kB/233.30 kB
⠙ Preparing packages... (0/3)0/3)
⠙ Preparing packages... (0/3)----- 183.67 kB/10.38 MB
⠙ Preparing packages... (0/3)----- 642.10 kB/10.38 MB
⠹ Preparing packages... (1/3)----- 1.08 MB/10.38 MB
⠹ Preparing packages... (1/3)----- 2.05 MB/10.38 MB
⠹ Preparing packages... (1/3)----- 2.55 MB/10.38 MB
⠹ Preparing packages... (1/3)----- 3.17 MB/10.38 MB
⠹ Preparing packages... (1/3)----- 4.04 MB/10.38 MB
⠸ Preparing packages... (1/3)----- 4.69 MB/10.38 MB
⠸ Preparing packages... (1/3)----- 6.17 MB/10.38 MB
⠸ Preparing packages... (1/3)----- 7.84 MB/10.38 MB
⠸ Preparing packages... (1/3)m---- 8.70 MB/10.38 MB
⠼ Preparing packages... (1/3)- 9.83 MB/10.38 MB
Building scipy==1.17.1
Building scipy==1.17.1
Building scipy==1.17.1
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: scipy==1.17.1
  Caused by: Failed to install requirements from `build-system.requires` (resolve)
  Caused by: No solution found when resolving: meson-python>=0.15.0, <0.21.0, cython>=3.0.8, <3.3.0, pybind11>=2.13.2, <3.1.0, pythran>=0.14.0, <0.19.0, numpy>=2.0.0, <2.7
  Caused by: Because pythran was not found in the package registry and you require pythran>=0.14.0,<0.19.0, we can conclude that your requirements are unsatisfiable.

In [47]:
import matplotlib.pyplot as plt
from datetime import datetime
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA

In [48]:
current_month_start = datetime.today().replace(day=1).date()
current_month_start

datetime.date(2026, 3, 1)

In [49]:
accounts['month_seq'] = pd.to_datetime(accounts['month_seq']).dt.date

In [50]:
latam_accounts = accounts[(accounts['region'] == 'LATAM') & (accounts['month_seq'] < current_month_start)].copy()
latam_accounts['month'] = latam_accounts['month_seq']
latam_accounts.head()

     month_seq region managed_region pillar_clean  unique_accounts       month
8   2018-05-01  LATAM           None         None               25  2018-05-01
9   2018-04-01  LATAM          LATAM      Digital               35  2018-04-01
15  2021-05-01  LATAM          LATAM           UC               19  2021-05-01
27  2015-11-01  LATAM           None           UC                2  2015-11-01
28  2017-02-01  LATAM          LATAM         None                6  2017-02-01

In [51]:
non_latam_accounts = accounts[(accounts['region'] != 'LATAM') & (accounts['month_seq'] < current_month_start)].copy()
non_latam_accounts['month'] = non_latam_accounts['month_seq']
non_latam_accounts.head()

    month_seq region managed_region pillar_clean  unique_accounts       month
0  2013-05-01   EMEA           EMEA      Digital               71  2013-05-01
1  2013-11-01   EMEA           None      Digital              383  2013-11-01
2  2022-08-01   EMEA           None    Platforms               91  2022-08-01
3  2025-06-01   APAC           None      Digital              435  2025-06-01
4  2024-08-01   APAC           None         None                4  2024-08-01

In [52]:
non_latam_accounts = non_latam_accounts.groupby('month').agg({'unique_accounts': 'sum'})
print(non_latam_accounts.sort_values(by='month', ascending=False))

            unique_accounts
month
2026-02-01             9468
2026-01-01             9431
2025-12-01             9406
2025-11-01             9359
2025-10-01             9294
...                     ...
2010-10-01               46
2010-09-01               30
2010-08-01               14
2010-07-01                8
2010-06-01                1

[189 rows x 1 columns]

Test if data is stationary

In [53]:
ts = pd.Series(
    non_latam_accounts['unique_accounts'].values,
    index=non_latam_accounts.index
)
log_ts = np.log(ts + 1)
diff_log_ts = log_ts.diff().dropna()

In [54]:
adf_result = adfuller(diff_log_ts)
print("ADF Statistic:", adf_result[0])
print("p-value:", adf_result[1])

ADF Statistic: -2.906222277809479
p-value: 0.044629201036050906

Model fitting

In [55]:
model = ARIMA(log_ts, order=(1, 1, 1)) 
fit_model = model.fit()

/home/bigdata/venv/lib64/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/home/bigdata/venv/lib64/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
/home/bigdata/venv/lib64/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)

In [56]:
print(fit_model.summary())

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  189
Model:                 ARIMA(1, 1, 1)   Log Likelihood                 198.080
Date:                Mon, 23 Mar 2026   AIC                           -390.161
Time:                        11:09:57   BIC                           -380.451
Sample:                    06-01-2010   HQIC                          -386.227
                         - 02-01-2026
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.9911      0.003    393.103      0.000       0.986       0.996
ma.L1         -0.2094      0.054     -3.910      0.000      -0.314      -0.104
sigma2         0.0070      0.000     38.026      0.000       0.007       0.007
===================================================================================
Ljung-Box (L1) (Q):                   3.05   Jarque-Bera (JB):             61541.94
Prob(Q):                              0.08   Prob(JB):                         0.00
Heteroskedasticity (H):               0.00   Skew:                            -7.83
Prob(H) (two-sided):                  0.00   Kurtosis:                        90.24
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [57]:
forecast_steps = 12
forecast = fit_model.forecast(steps=forecast_steps)
print(forecast)

2026-03-01    9.159505
2026-04-01    9.163198
2026-05-01    9.166858
2026-06-01    9.170486
2026-07-01    9.174082
2026-08-01    9.177646
2026-09-01    9.181179
2026-10-01    9.184680
2026-11-01    9.188150
2026-12-01    9.191589
2027-01-01    9.194998
2027-02-01    9.198376
Freq: MS, Name: predicted_mean, dtype: float64

In [58]:
forecast_exp = np.exp(forecast) - 1  
print(forecast_exp)

2026-03-01    9503.348897
2026-04-01    9538.514762
2026-05-01    9573.497393
2026-06-01    9608.296611
2026-07-01    9642.912259
2026-08-01    9677.344204
2026-09-01    9711.592335
2026-10-01    9745.656561
2026-11-01    9779.536814
2026-12-01    9813.233047
2027-01-01    9846.745234
2027-02-01    9880.073368
Freq: MS, Name: predicted_mean, dtype: float64

In [59]:
future_months = pd.date_range(start=current_month_start, periods=12, freq='MS')
print(future_months)

DatetimeIndex(['2026-03-01', '2026-04-01', '2026-05-01', '2026-06-01',
               '2026-07-01', '2026-08-01', '2026-09-01', '2026-10-01',
               '2026-11-01', '2026-12-01', '2027-01-01', '2027-02-01'],
              dtype='datetime64[ns]', freq='MS')

In [60]:
forecast_df = pd.DataFrame({
    'month': future_months,
    'unique_accounts': forecast_exp.values,
    'type': 'Forecast'
})
print(forecast_df)

        month  unique_accounts      type
0  2026-03-01      9503.348897  Forecast
1  2026-04-01      9538.514762  Forecast
2  2026-05-01      9573.497393  Forecast
3  2026-06-01      9608.296611  Forecast
4  2026-07-01      9642.912259  Forecast
5  2026-08-01      9677.344204  Forecast
6  2026-09-01      9711.592335  Forecast
7  2026-10-01      9745.656561  Forecast
8  2026-11-01      9779.536814  Forecast
9  2026-12-01      9813.233047  Forecast
10 2027-01-01      9846.745234  Forecast
11 2027-02-01      9880.073368  Forecast

In [61]:
actuals_df = non_latam_accounts.copy()
actuals_df = actuals_df.reset_index()  
actuals_df['type'] = 'Actual'
print(actuals_df)

          month  unique_accounts    type
0    2010-06-01                1  Actual
1    2010-07-01                8  Actual
2    2010-08-01               14  Actual
3    2010-09-01               30  Actual
4    2010-10-01               46  Actual
..          ...              ...     ...
184  2025-10-01             9294  Actual
185  2025-11-01             9359  Actual
186  2025-12-01             9406  Actual
187  2026-01-01             9431  Actual
188  2026-02-01             9468  Actual

[189 rows x 3 columns]

In [62]:
actuals_df['month'] = pd.to_datetime(actuals_df['month'])
forecast_df['month'] = pd.to_datetime(forecast_df['month'])
combined_df = pd.concat([actuals_df, forecast_df])
print(combined_df)

        month  unique_accounts      type
0  2010-06-01         1.000000    Actual
1  2010-07-01         8.000000    Actual
2  2010-08-01        14.000000    Actual
3  2010-09-01        30.000000    Actual
4  2010-10-01        46.000000    Actual
..        ...              ...       ...
7  2026-10-01      9745.656561  Forecast
8  2026-11-01      9779.536814  Forecast
9  2026-12-01      9813.233047  Forecast
10 2027-01-01      9846.745234  Forecast
11 2027-02-01      9880.073368  Forecast

[201 rows x 3 columns]

In [63]:
combined_df.to_csv('non_latam_accounts_forecast.csv', index=False)

In [64]:
!hdfs dfs -put -f non_latam_accounts_forecast.csv /user/{username}/notebooks/Workload\ Projections/Forecasted\ data

In [65]:
!hdfs dfs -put -f non_latam_accounts_forecast.csv /user/{username}/notebooks/adyen_downloader

## Squads Forecasting

### Service cases

In [66]:
def create_service_cases_df(df):

    df['month'] = pd.to_datetime(df['month'])

    filtered_df = df[
        (df['month'].dt.date < current_month_start) &
        (df['month'].dt.date >= pd.to_datetime('2023-09-01').date()) &
        (~df['origin'].isin(['Side Conversation', 'Call'])) &
        (df['category'] == 'Service')
    ]

    service_df = (
        filtered_df
        .groupby(['month', 'support_team'], as_index=False)
        .agg(cases=('unique_id_count', 'sum'))
        .dropna()
    )

    service_df = service_df.rename(columns={
        'month': 'month',
        'support_team': 'squad',
        'cases': 'cases'
    })

    return service_df

In [67]:
service_df = create_service_cases_df(tickets)
print(service_df)

         month                        squad  cases
0   2023-09-01     Account Setup Operations   3031
1   2023-09-01                     Disputes   1561
2   2023-09-01                     Ecom APM    736
3   2023-09-01                   Ecom Cards   1045
4   2023-09-01                    Ecom Core   2300
..         ...                          ...    ...
503 2026-02-01  LATAM - Operational Support   1358
504 2026-02-01    LATAM - Technical Support    442
505 2026-02-01          Operational Support   5942
506 2026-02-01              Partner Support    208
507 2026-02-01                    Platforms    976

[508 rows x 3 columns]

In [68]:
def prepare_forecast_df(service_df, account_growth):
    df = (
        service_df
        .merge(account_growth, on='month', how='left')
        .rename(columns={'month': 'ds', 'cases': 'y'})
        .dropna(subset=['ds', 'y', 'unique_accounts'])
    )
    return df

In [69]:
test = prepare_forecast_df(service_df, combined_df)
print(test)

            ds                        squad     y  unique_accounts    type
0   2023-09-01     Account Setup Operations  3031           7899.0  Actual
1   2023-09-01                     Disputes  1561           7899.0  Actual
2   2023-09-01                     Ecom APM   736           7899.0  Actual
3   2023-09-01                   Ecom Cards  1045           7899.0  Actual
4   2023-09-01                    Ecom Core  2300           7899.0  Actual
..         ...                          ...   ...              ...     ...
503 2026-02-01  LATAM - Operational Support  1358           9468.0  Actual
504 2026-02-01    LATAM - Technical Support   442           9468.0  Actual
505 2026-02-01          Operational Support  5942           9468.0  Actual
506 2026-02-01              Partner Support   208           9468.0  Actual
507 2026-02-01                    Platforms   976           9468.0  Actual

[508 rows x 5 columns]

In [70]:
nested_df = {
    squad: df.drop(columns='squad')
    for squad, df in test.groupby('squad')
}
print(nested_df)

{'Account Setup Operations':             ds     y  unique_accounts    type
0   2023-09-01  3031           7899.0  Actual
14  2023-10-01  3042           7963.0  Actual
29  2023-11-01  3140           8044.0  Actual
44  2023-12-01  2198           8095.0  Actual
59  2024-01-01  2720           8123.0  Actual
73  2024-02-01  2535           8157.0  Actual
88  2024-03-01  2636           8209.0  Actual
104 2024-04-01  2868           8300.0  Actual
120 2024-05-01  2858           8389.0  Actual
136 2024-06-01  2622           8436.0  Actual
152 2024-07-01  2843           8488.0  Actual
168 2024-08-01  2530           8503.0  Actual
185 2024-09-01  2832           8569.0  Actual
202 2024-10-01  3363           8647.0  Actual
220 2024-11-01  3066           8711.0  Actual
238 2024-12-01  2397           8756.0  Actual
256 2025-01-01  2754           8821.0  Actual
274 2025-02-01  2662           8865.0  Actual
292 2025-03-01  2955           8945.0  Actual
310 2025-04-01  2924           8998.0  Actual
328 2025-05-01  3027           9050.0  Actual
346 2025-06-01  2913           9102.0  Actual
364 2025-07-01  3115           9156.0  Actual
382 2025-08-01  2559           9186.0  Actual
400 2025-09-01  2887           9252.0  Actual
418 2025-10-01  3202           9294.0  Actual
436 2025-11-01  2806           9359.0  Actual
454 2025-12-01  2448           9406.0  Actual
472 2026-01-01  2435           9431.0  Actual
490 2026-02-01  2497           9468.0  Actual, 'China':             ds   y  unique_accounts    type
15  2023-10-01   1           7963.0  Actual
30  2023-11-01   1           8044.0  Actual
45  2023-12-01   1           8095.0  Actual
74  2024-02-01   2           8157.0  Actual
89  2024-03-01   7           8209.0  Actual
105 2024-04-01  26           8300.0  Actual
121 2024-05-01  38           8389.0  Actual
137 2024-06-01  43           8436.0  Actual
153 2024-07-01  39           8488.0  Actual
169 2024-08-01  34           8503.0  Actual
186 2024-09-01  22           8569.0  Actual
203 2024-10-01  22           8647.0  Actual
221 2024-11-01  20           8711.0  Actual
239 2024-12-01  27           8756.0  Actual
257 2025-01-01  20           8821.0  Actual
275 2025-02-01  28           8865.0  Actual
293 2025-03-01  34           8945.0  Actual
311 2025-04-01  32           8998.0  Actual
329 2025-05-01  17           9050.0  Actual
347 2025-06-01  30           9102.0  Actual
365 2025-07-01  33           9156.0  Actual
383 2025-08-01  28           9186.0  Actual
401 2025-09-01  41           9252.0  Actual
419 2025-10-01  32           9294.0  Actual
437 2025-11-01  38           9359.0  Actual
455 2025-12-01  48           9406.0  Actual
473 2026-01-01  31           9431.0  Actual
491 2026-02-01  23           9468.0  Actual, 'Disputes':             ds     y  unique_accounts    type
1   2023-09-01  1561           7899.0  Actual
16  2023-10-01  2732           7963.0  Actual
31  2023-11-01  1696           8044.0  Actual
46  2023-12-01  1371           8095.0  Actual
60  2024-01-01  1398           8123.0  Actual
75  2024-02-01  1747           8157.0  Actual
90  2024-03-01  1859           8209.0  Actual
106 2024-04-01  1862           8300.0  Actual
122 2024-05-01  1985           8389.0  Actual
138 2024-06-01  1540           8436.0  Actual
154 2024-07-01  1930           8488.0  Actual
170 2024-08-01  1799           8503.0  Actual
187 2024-09-01  1933           8569.0  Actual
204 2024-10-01  2166           8647.0  Actual
222 2024-11-01  1781           8711.0  Actual
240 2024-12-01  1841           8756.0  Actual
258 2025-01-01  2173           8821.0  Actual
276 2025-02-01  1907           8865.0  Actual
294 2025-03-01  2581           8945.0  Actual
312 2025-04-01  2278           8998.0  Actual
330 2025-05-01  2612           9050.0  Actual
348 2025-06-01  2791           9102.0  Actual
366 2025-07-01  3033           9156.0  Actual
384 2025-08-01  2307           9186.0  Actual
402 2025-09-01  2112           9252.0  Actual
420 2025-10-01  1984           9294.0  Actual
438 2025-11-01  1830           9359.0  Actual
456 2025-12-01  1893           9406.0  Actual
474 2026-01-01  2146           9431.0  Actual
492 2026-02-01  1873           9468.0  Actual, 'Ecom APM':             ds     y  unique_accounts    type
2   2023-09-01   736           7899.0  Actual
17  2023-10-01   711           7963.0  Actual
32  2023-11-01   745           8044.0  Actual
47  2023-12-01   575           8095.0  Actual
61  2024-01-01   799           8123.0  Actual
76  2024-02-01   752           8157.0  Actual
91  2024-03-01   739           8209.0  Actual
107 2024-04-01   862           8300.0  Actual
123 2024-05-01   823           8389.0  Actual
139 2024-06-01   876           8436.0  Actual
155 2024-07-01  1030           8488.0  Actual
171 2024-08-01   870           8503.0  Actual
188 2024-09-01  1003           8569.0  Actual
205 2024-10-01  1123           8647.0  Actual
223 2024-11-01  1084           8711.0  Actual
241 2024-12-01   868           8756.0  Actual
259 2025-01-01  1168           8821.0  Actual
277 2025-02-01  1048           8865.0  Actual
295 2025-03-01  1289           8945.0  Actual
313 2025-04-01  1171           8998.0  Actual
331 2025-05-01   976           9050.0  Actual
349 2025-06-01   937           9102.0  Actual
367 2025-07-01   966           9156.0  Actual
385 2025-08-01   961           9186.0  Actual
403 2025-09-01  1001           9252.0  Actual
421 2025-10-01  1098           9294.0  Actual
439 2025-11-01  1004           9359.0  Actual
457 2025-12-01   920           9406.0  Actual
475 2026-01-01   939           9431.0  Actual
493 2026-02-01  1026           9468.0  Actual, 'Ecom Cards':             ds     y  unique_accounts    type
3   2023-09-01  1045           7899.0  Actual
18  2023-10-01   952           7963.0  Actual
33  2023-11-01  1040           8044.0  Actual
48  2023-12-01   833           8095.0  Actual
62  2024-01-01  1098           8123.0  Actual
77  2024-02-01  1108           8157.0  Actual
92  2024-03-01  1119           8209.0  Actual
108 2024-04-01  1145           8300.0  Actual
124 2024-05-01  1251           8389.0  Actual
140 2024-06-01  1113           8436.0  Actual
156 2024-07-01  1238           8488.0  Actual
172 2024-08-01  1350           8503.0  Actual
189 2024-09-01  1551           8569.0  Actual
206 2024-10-01  1721           8647.0  Actual
224 2024-11-01  1593           8711.0  Actual
242 2024-12-01  1365           8756.0  Actual
260 2025-01-01  1729           8821.0  Actual
278 2025-02-01  1816           8865.0  Actual
296 2025-03-01  1991           8945.0  Actual
314 2025-04-01  1954           8998.0  Actual
332 2025-05-01  2002           9050.0  Actual
350 2025-06-01  1843           9102.0  Actual
368 2025-07-01  2072           9156.0  Actual
386 2025-08-01  1774           9186.0  Actual
404 2025-09-01  1813           9252.0  Actual
422 2025-10-01  1862           9294.0  Actual
440 2025-11-01  1743           9359.0  Actual
458 2025-12-01  1571           9406.0  Actual
476 2026-01-01  1832           9431.0  Actual
494 2026-02-01  1751           9468.0  Actual, 'Ecom Core':             ds     y  unique_accounts    type
4   2023-09-01  2300           7899.0  Actual
19  2023-10-01  2301           7963.0  Actual
34  2023-11-01  2146           8044.0  Actual
49  2023-12-01  1541           8095.0  Actual
63  2024-01-01  2043           8123.0  Actual
78  2024-02-01  1957           8157.0  Actual
93  2024-03-01  1847           8209.0  Actual
109 2024-04-01  1914           8300.0  Actual
125 2024-05-01  1998           8389.0  Actual
141 2024-06-01  1652           8436.0  Actual
157 2024-07-01  1643           8488.0  Actual
173 2024-08-01  1720           8503.0  Actual
190 2024-09-01  1472           8569.0  Actual
207 2024-10-01  1410           8647.0  Actual
225 2024-11-01  1342           8711.0  Actual
243 2024-12-01  1327           8756.0  Actual
261 2025-01-01  1453           8821.0  Actual
279 2025-02-01  1341           8865.0  Actual
297 2025-03-01  1661           8945.0  Actual
315 2025-04-01  1650           8998.0  Actual
333 2025-05-01  1522           9050.0  Actual
351 2025-06-01  1503           9102.0  Actual
369 2025-07-01  1667           9156.0  Actual
387 2025-08-01  1567           9186.0  Actual
405 2025-09-01  1539           9252.0  Actual
423 2025-10-01  1615           9294.0  Actual
441 2025-11-01  1445           9359.0  Actual
459 2025-12-01  1259           9406.0  Actual
477 2026-01-01  1418           9431.0  Actual
495 2026-02-01  1344           9468.0  Actual, 'Ecom Integration':             ds     y  unique_accounts    type
5   2023-09-01  1017           7899.0  Actual
20  2023-10-01   954           7963.0  Actual
35  2023-11-01   976           8044.0  Actual
50  2023-12-01   832           8095.0  Actual
64  2024-01-01  1096           8123.0  Actual
79  2024-02-01  1100           8157.0  Actual
94  2024-03-01  1182           8209.0  Actual
110 2024-04-01  1219           8300.0  Actual
126 2024-05-01  1186           8389.0  Actual
142 2024-06-01  1182           8436.0  Actual
158 2024-07-01  1256           8488.0  Actual
174 2024-08-01  1197           8503.0  Actual
191 2024-09-01  1191           8569.0  Actual
208 2024-10-01  1353           8647.0  Actual
226 2024-11-01  1254           8711.0  Actual
244 2024-12-01   940           8756.0  Actual
262 2025-01-01  1169           8821.0  Actual
280 2025-02-01  1086           8865.0  Actual
298 2025-03-01  1260           8945.0  Actual
316 2025-04-01  1176           8998.0  Actual
334 2025-05-01  1030           9050.0  Actual
352 2025-06-01   995           9102.0  Actual
370 2025-07-01  1086           9156.0  Actual
388 2025-08-01   899           9186.0  Actual
406 2025-09-01  1096           9252.0  Actual
424 2025-10-01  1050           9294.0  Actual
442 2025-11-01   888           9359.0  Actual
460 2025-12-01   759           9406.0  Actual
478 2026-01-01   853           9431.0  Actual
496 2026-02-01   831           9468.0  Actual, 'Finance':             ds     y  unique_accounts    type
6   2023-09-01  1147           7899.0  Actual
21  2023-10-01  1767           7963.0  Actual
36  2023-11-01  1779           8044.0  Actual
51  2023-12-01  1647           8095.0  Actual
65  2024-01-01  1945           8123.0  Actual
80  2024-02-01  1708           8157.0  Actual
95  2024-03-01  1766           8209.0  Actual
111 2024-04-01  1959           8300.0  Actual
127 2024-05-01  2088           8389.0  Actual
143 2024-06-01  1807           8436.0  Actual
159 2024-07-01  2039           8488.0  Actual
175 2024-08-01  1958           8503.0  Actual
192 2024-09-01  1839           8569.0  Actual
209 2024-10-01  2070           8647.0  Actual
227 2024-11-01  1884           8711.0  Actual
245 2024-12-01  1832           8756.0  Actual
263 2025-01-01  2313           8821.0  Actual
281 2025-02-01  2098           8865.0  Actual
299 2025-03-01  2254           8945.0  Actual
317 2025-04-01  2134           8998.0  Actual
335 2025-05-01  2223           9050.0  Actual
353 2025-06-01  2031           9102.0  Actual
371 2025-07-01  2179           9156.0  Actual
389 2025-08-01  1962           9186.0  Actual
407 2025-09-01  2236           9252.0  Actual
425 2025-10-01  2166           9294.0  Actual
443 2025-11-01  2093           9359.0  Actual
461 2025-12-01  1922           9406.0  Actual
479 2026-01-01  1923           9431.0  Actual
497 2026-02-01  1821           9468.0  Actual, 'IPP Adv. Payments':             ds     y  unique_accounts    type
7   2023-09-01  1016           7899.0  Actual
22  2023-10-01  1008           7963.0  Actual
37  2023-11-01  1199           8044.0  Actual
52  2023-12-01   988           8095.0  Actual
66  2024-01-01  1057           8123.0  Actual
81  2024-02-01   955           8157.0  Actual
96  2024-03-01  1100           8209.0  Actual
112 2024-04-01  1234           8300.0  Actual
128 2024-05-01  1199           8389.0  Actual
144 2024-06-01  1153           8436.0  Actual
160 2024-07-01  1232           8488.0  Actual
176 2024-08-01  1115           8503.0  Actual
193 2024-09-01  1160           8569.0  Actual
210 2024-10-01  1435           8647.0  Actual
228 2024-11-01  1292           8711.0  Actual
246 2024-12-01  1094           8756.0  Actual
264 2025-01-01  1233           8821.0  Actual
282 2025-02-01  1213           8865.0  Actual
300 2025-03-01  1336           8945.0  Actual
318 2025-04-01  1274           8998.0  Actual
336 2025-05-01  1245           9050.0  Actual
354 2025-06-01  1205           9102.0  Actual
372 2025-07-01  1236           9156.0  Actual
390 2025-08-01  1198           9186.0  Actual
408 2025-09-01  1318           9252.0  Actual
426 2025-10-01  1431           9294.0  Actual
444 2025-11-01  1359           9359.0  Actual
462 2025-12-01  1243           9406.0  Actual
480 2026-01-01  1289           9431.0  Actual
498 2026-02-01  1253           9468.0  Actual, 'IPP Core':             ds     y  unique_accounts    type
8   2023-09-01  1581           7899.0  Actual
23  2023-10-01  1855           7963.0  Actual
38  2023-11-01  1771           8044.0  Actual
53  2023-12-01  1299           8095.0  Actual
67  2024-01-01  1385           8123.0  Actual
82  2024-02-01  1257           8157.0  Actual
97  2024-03-01  1252           8209.0  Actual
113 2024-04-01  1350           8300.0  Actual
129 2024-05-01  1410           8389.0  Actual
145 2024-06-01  1264           8436.0  Actual
161 2024-07-01  1636           8488.0  Actual
177 2024-08-01  1456           8503.0  Actual
194 2024-09-01  1323           8569.0  Actual
211 2024-10-01  1478           8647.0  Actual
229 2024-11-01  1313           8711.0  Actual
247 2024-12-01  1122           8756.0  Actual
265 2025-01-01  1400           8821.0  Actual
283 2025-02-01  1321           8865.0  Actual
301 2025-03-01  1505           8945.0  Actual
319 2025-04-01  1609           8998.0  Actual
337 2025-05-01  1587           9050.0  Actual
355 2025-06-01  1425           9102.0  Actual
373 2025-07-01  1518           9156.0  Actual
391 2025-08-01  1310           9186.0  Actual
409 2025-09-01  1348           9252.0  Actual
427 2025-10-01  1453           9294.0  Actual
445 2025-11-01  1419           9359.0  Actual
463 2025-12-01  1180           9406.0  Actual
481 2026-01-01  1332           9431.0  Actual
499 2026-02-01  1293           9468.0  Actual, 'IPP Integrations':             ds    y  unique_accounts    type
9   2023-09-01  397           7899.0  Actual
24  2023-10-01  342           7963.0  Actual
39  2023-11-01  320           8044.0  Actual
54  2023-12-01  274           8095.0  Actual
68  2024-01-01  346           8123.0  Actual
83  2024-02-01  356           8157.0  Actual
98  2024-03-01  380           8209.0  Actual
114 2024-04-01  331           8300.0  Actual
130 2024-05-01  361           8389.0  Actual
146 2024-06-01  387           8436.0  Actual
162 2024-07-01  445           8488.0  Actual
178 2024-08-01  443           8503.0  Actual
195 2024-09-01  449           8569.0  Actual
212 2024-10-01  535           8647.0  Actual
230 2024-11-01  516           8711.0  Actual
248 2024-12-01  446           8756.0  Actual
266 2025-01-01  528           8821.0  Actual
284 2025-02-01  554           8865.0  Actual
302 2025-03-01  680           8945.0  Actual
320 2025-04-01  695           8998.0  Actual
338 2025-05-01  693           9050.0  Actual
356 2025-06-01  635           9102.0  Actual
374 2025-07-01  715           9156.0  Actual
392 2025-08-01  585           9186.0  Actual
410 2025-09-01  754           9252.0  Actual
428 2025-10-01  720           9294.0  Actual
446 2025-11-01  734           9359.0  Actual
464 2025-12-01  558           9406.0  Actual
482 2026-01-01  672           9431.0  Actual
500 2026-02-01  581           9468.0  Actual, 'India - Technical Support':             ds   y  unique_accounts    type
179 2024-08-01  29           8503.0  Actual
196 2024-09-01  27           8569.0  Actual
213 2024-10-01  37           8647.0  Actual
231 2024-11-01  46           8711.0  Actual
249 2024-12-01  47           8756.0  Actual
267 2025-01-01  47           8821.0  Actual
285 2025-02-01  55           8865.0  Actual
303 2025-03-01  77           8945.0  Actual
321 2025-04-01  67           8998.0  Actual
339 2025-05-01  62           9050.0  Actual
357 2025-06-01  67           9102.0  Actual
375 2025-07-01  80           9156.0  Actual
393 2025-08-01  69           9186.0  Actual
411 2025-09-01  57           9252.0  Actual
429 2025-10-01  89           9294.0  Actual
447 2025-11-01  99           9359.0  Actual
465 2025-12-01  75           9406.0  Actual
483 2026-01-01  59           9431.0  Actual
501 2026-02-01  73           9468.0  Actual, 'Japan':             ds   y  unique_accounts    type
99  2024-03-01   4           8209.0  Actual
115 2024-04-01  11           8300.0  Actual
131 2024-05-01  11           8389.0  Actual
147 2024-06-01  17           8436.0  Actual
163 2024-07-01  15           8488.0  Actual
180 2024-08-01  11           8503.0  Actual
197 2024-09-01   8           8569.0  Actual
214 2024-10-01   6           8647.0  Actual
232 2024-11-01  16           8711.0  Actual
250 2024-12-01  11           8756.0  Actual
268 2025-01-01   9           8821.0  Actual
286 2025-02-01  18           8865.0  Actual
304 2025-03-01  16           8945.0  Actual
322 2025-04-01  26           8998.0  Actual
340 2025-05-01  21           9050.0  Actual
358 2025-06-01  14           9102.0  Actual
376 2025-07-01  28           9156.0  Actual
394 2025-08-01  29           9186.0  Actual
412 2025-09-01  48           9252.0  Actual
430 2025-10-01  37           9294.0  Actual
448 2025-11-01  26           9359.0  Actual
466 2025-12-01  37           9406.0  Actual
484 2026-01-01  25           9431.0  Actual
502 2026-02-01  37           9468.0  Actual, 'LATAM - Operational Support':             ds     y  unique_accounts    type
10  2023-09-01   579           7899.0  Actual
25  2023-10-01   442           7963.0  Actual
40  2023-11-01   295           8044.0  Actual
55  2023-12-01   409           8095.0  Actual
69  2024-01-01   379           8123.0  Actual
84  2024-02-01   337           8157.0  Actual
100 2024-03-01   352           8209.0  Actual
116 2024-04-01   423           8300.0  Actual
132 2024-05-01   511           8389.0  Actual
148 2024-06-01   400           8436.0  Actual
164 2024-07-01   457           8488.0  Actual
181 2024-08-01   544           8503.0  Actual
198 2024-09-01   502           8569.0  Actual
215 2024-10-01   474           8647.0  Actual
233 2024-11-01   431           8711.0  Actual
251 2024-12-01   281           8756.0  Actual
269 2025-01-01   397           8821.0  Actual
287 2025-02-01   420           8865.0  Actual
305 2025-03-01   395           8945.0  Actual
323 2025-04-01   531           8998.0  Actual
341 2025-05-01   447           9050.0  Actual
359 2025-06-01   348           9102.0  Actual
377 2025-07-01   452           9156.0  Actual
395 2025-08-01   353           9186.0  Actual
413 2025-09-01   360           9252.0  Actual
431 2025-10-01   674           9294.0  Actual
449 2025-11-01   673           9359.0  Actual
467 2025-12-01  1174           9406.0  Actual
485 2026-01-01   989           9431.0  Actual
503 2026-02-01  1358           9468.0  Actual, 'LATAM - Technical Support':             ds    y  unique_accounts    type
11  2023-09-01  509           7899.0  Actual
26  2023-10-01  520           7963.0  Actual
41  2023-11-01  672           8044.0  Actual
56  2023-12-01  515           8095.0  Actual
70  2024-01-01  657           8123.0  Actual
85  2024-02-01  627           8157.0  Actual
101 2024-03-01  702           8209.0  Actual
117 2024-04-01  704           8300.0  Actual
133 2024-05-01  752           8389.0  Actual
149 2024-06-01  695           8436.0  Actual
165 2024-07-01  792           8488.0  Actual
182 2024-08-01  912           8503.0  Actual
199 2024-09-01  827           8569.0  Actual
216 2024-10-01  848           8647.0  Actual
234 2024-11-01  814           8711.0  Actual
252 2024-12-01  617           8756.0  Actual

In [71]:
def run_service_prophet(df, account_growth):
    
     # Ensure required columns are present
    required_cols = {'ds', 'y', 'unique_accounts'}
    if not required_cols.issubset(df.columns):
        return None
    
    # Remove NAs and check row count
    df = df.dropna(subset=['ds', 'y', 'unique_accounts'])
    if len(df) < 10:
        return None  # Prophet requires enough data points
    
    # Fit the model with regressor
    m = Prophet()
    m.add_regressor('unique_accounts', prior_scale=0.1)
    m.fit(df)
    
    # Make future df
    future = m.make_future_dataframe(periods=13, freq='M')
    future = future.drop_duplicates(subset=['ds'])
    future['ds'] = future['ds'].values.astype('datetime64[M]')
    
    # Ensure account_growth has no NaNs
    account_growth = account_growth.dropna(subset=['month', 'unique_accounts'])
    account_growth = account_growth.rename(columns={'month': 'ds'})
    
    # Ensure datetime format matches for merging
    future['ds'] = pd.to_datetime(future['ds'])
    account_growth['ds'] = pd.to_datetime(account_growth['ds'])
    
    # Join with account_growth on 'ds'
    future = future.merge(account_growth, on='ds', how='left')
    future['unique_accounts'] = future['unique_accounts'].fillna(method='ffill')
    future['unique_accounts'] = future['unique_accounts'].fillna(0)
    
    future = future[['ds', 'unique_accounts']]
    
    # Forecast
    forecast = m.predict(future)
    last_train_date = df['ds'].max()
    forecast = forecast[forecast['ds'] > last_train_date]
    
    # Model evaluation on historical part
    comparison = df.merge(forecast[['ds', 'yhat']], on='ds', how='left').dropna()
    comparison['residuals'] = comparison['y'] - comparison['yhat']

    ss_res = np.sum(comparison['residuals'] ** 2)
    ss_tot = np.sum((comparison['y'] - np.mean(comparison['y'])) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else None

    mape = np.mean(np.abs((comparison['y'] - comparison['yhat']) / comparison['y'])) * 100

    return {
        'model': m,
        'forecast': forecast,
        'r_squared': r_squared,
        'mape': mape
    }

In [72]:
results = {}
for squad, df in nested_df.items():
    result = run_service_prophet(df, combined_df)
    if result is not None:
        results[squad] = result
print(results)

[I 2026-03-23 11:10:07,669.669 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:07,669.669 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:07,698.698 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:07,702.702 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/8vu_pth8.json
[D 2026-03-23 11:10:07,705.705 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/njmr_18t.json
[D 2026-03-23 11:10:07,707.707 cmdstanpy] idx 0
[D 2026-03-23 11:10:07,707.707 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:07,707.707 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=2222', 'data', 'file=/tmp/tmpy_ntexaz/8vu_pth8.json', 'init=/tmp/tmpy_ntexaz/njmr_18t.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeleqtktwr7/prophet_model-20260323111007.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:07,707.707 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:07,942.942 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:08,033.033 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:08,033.033 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:08,053.053 prophet] n_changepoints greater than number of observations. Using 21.
[D 2026-03-23 11:10:08,056.056 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/5whfru_3.json
[D 2026-03-23 11:10:08,059.059 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/qjly2wug.json
[D 2026-03-23 11:10:08,060.060 cmdstanpy] idx 0
[D 2026-03-23 11:10:08,060.060 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:08,060.060 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=7757', 'data', 'file=/tmp/tmpy_ntexaz/5whfru_3.json', 'init=/tmp/tmpy_ntexaz/qjly2wug.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model_3somzls/prophet_model-20260323111008.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:08,060.060 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:08,206.206 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:08,310.310 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:08,310.310 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:08,326.326 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:08,333.333 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/5ctcenhv.json
[D 2026-03-23 11:10:08,336.336 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/q65yhk7x.json
[D 2026-03-23 11:10:08,337.337 cmdstanpy] idx 0
[D 2026-03-23 11:10:08,337.337 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:08,337.337 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=34076', 'data', 'file=/tmp/tmpy_ntexaz/5ctcenhv.json', 'init=/tmp/tmpy_ntexaz/q65yhk7x.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeli8tx6u8q/prophet_model-20260323111008.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:08,337.337 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:08,503.503 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:08,582.582 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:08,582.582 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:08,597.597 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:08,601.601 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/kf7_br92.json
[D 2026-03-23 11:10:08,604.604 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/lessbr01.json
[D 2026-03-23 11:10:08,605.605 cmdstanpy] idx 0
[D 2026-03-23 11:10:08,605.605 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:08,605.605 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=88289', 'data', 'file=/tmp/tmpy_ntexaz/kf7_br92.json', 'init=/tmp/tmpy_ntexaz/lessbr01.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model6_dn9ol8/prophet_model-20260323111008.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:08,605.605 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:08,803.803 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:08,883.883 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:08,883.883 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:08,900.900 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:08,904.904 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/znzv1vqr.json
[D 2026-03-23 11:10:08,909.909 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/jp5gw1lg.json
[D 2026-03-23 11:10:08,910.910 cmdstanpy] idx 0
[D 2026-03-23 11:10:08,910.910 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:08,910.910 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=19172', 'data', 'file=/tmp/tmpy_ntexaz/znzv1vqr.json', 'init=/tmp/tmpy_ntexaz/jp5gw1lg.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model0nhbznrw/prophet_model-20260323111008.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:08,910.910 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:09,178.178 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:09,275.275 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:09,275.275 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:09,293.293 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:09,297.297 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/5hc3v6dz.json
[D 2026-03-23 11:10:09,301.301 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/wvsdbjlx.json
[D 2026-03-23 11:10:09,301.301 cmdstanpy] idx 0
[D 2026-03-23 11:10:09,301.301 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:09,301.301 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=24698', 'data', 'file=/tmp/tmpy_ntexaz/5hc3v6dz.json', 'init=/tmp/tmpy_ntexaz/wvsdbjlx.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeleyfg36zn/prophet_model-20260323111009.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:09,301.301 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:09,634.634 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:09,722.722 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:09,722.722 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:09,735.735 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:09,738.738 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/cgcrwqs8.json
[D 2026-03-23 11:10:09,741.741 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/0y4el0o9.json
[D 2026-03-23 11:10:09,741.741 cmdstanpy] idx 0
[D 2026-03-23 11:10:09,741.741 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:09,741.741 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=92049', 'data', 'file=/tmp/tmpy_ntexaz/cgcrwqs8.json', 'init=/tmp/tmpy_ntexaz/0y4el0o9.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelwkj76ibf/prophet_model-20260323111009.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:09,741.741 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:09,977.977 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:10,054.054 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:10,054.054 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:10,068.068 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:10,070.070 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/3z9e0crp.json
[D 2026-03-23 11:10:10,073.073 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/y3ei3h9e.json
[D 2026-03-23 11:10:10,073.073 cmdstanpy] idx 0
[D 2026-03-23 11:10:10,074.074 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:10,074.074 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=14760', 'data', 'file=/tmp/tmpy_ntexaz/3z9e0crp.json', 'init=/tmp/tmpy_ntexaz/y3ei3h9e.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelwduvfftn/prophet_model-20260323111010.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:10,074.074 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:10,299.299 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:10,374.374 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:10,374.374 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:10,388.388 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:10,391.391 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/1l67qkj6.json
[D 2026-03-23 11:10:10,394.394 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/uez3w2vv.json
[D 2026-03-23 11:10:10,395.395 cmdstanpy] idx 0
[D 2026-03-23 11:10:10,395.395 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:10,395.395 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=15333', 'data', 'file=/tmp/tmpy_ntexaz/1l67qkj6.json', 'init=/tmp/tmpy_ntexaz/uez3w2vv.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelbmyh0nvm/prophet_model-20260323111010.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:10,395.395 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:10,669.669 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:10,754.754 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:10,754.754 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:10,768.768 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:10,771.771 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/v5__f_8t.json
[D 2026-03-23 11:10:10,773.773 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/v_4dt6ro.json
[D 2026-03-23 11:10:10,776.776 cmdstanpy] idx 0
[D 2026-03-23 11:10:10,776.776 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:10,776.776 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=50695', 'data', 'file=/tmp/tmpy_ntexaz/v5__f_8t.json', 'init=/tmp/tmpy_ntexaz/v_4dt6ro.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeld_077oao/prophet_model-20260323111010.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:10,776.776 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:11,034.034 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:11,125.125 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:11,126.126 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:11,138.138 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:11,141.141 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/_09kil0u.json
[D 2026-03-23 11:10:11,144.144 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/1ij8kkjf.json
[D 2026-03-23 11:10:11,144.144 cmdstanpy] idx 0
[D 2026-03-23 11:10:11,145.145 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:11,145.145 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=652', 'data', 'file=/tmp/tmpy_ntexaz/_09kil0u.json', 'init=/tmp/tmpy_ntexaz/1ij8kkjf.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelbjb5m3_f/prophet_model-20260323111011.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:11,145.145 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:11,344.344 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:11,438.438 prophet] Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
[I 2026-03-23 11:10:11,438.438 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:11,438.438 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:11,450.450 prophet] n_changepoints greater than number of observations. Using 14.
[D 2026-03-23 11:10:11,452.452 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/byxe6k8m.json
[D 2026-03-23 11:10:11,452.452 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/j_0h1r1h.json
[D 2026-03-23 11:10:11,453.453 cmdstanpy] idx 0
[D 2026-03-23 11:10:11,453.453 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:11,453.453 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=36549', 'data', 'file=/tmp/tmpy_ntexaz/byxe6k8m.json', 'init=/tmp/tmpy_ntexaz/j_0h1r1h.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelyoof3pjb/prophet_model-20260323111011.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:11,453.453 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:11,523.523 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:11,598.598 prophet] Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
[I 2026-03-23 11:10:11,598.598 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:11,598.598 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:11,611.611 prophet] n_changepoints greater than number of observations. Using 18.
[D 2026-03-23 11:10:11,613.613 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/40layo8x.json
[D 2026-03-23 11:10:11,614.614 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/tggki_pd.json
[D 2026-03-23 11:10:11,614.614 cmdstanpy] idx 0
[D 2026-03-23 11:10:11,614.614 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:11,614.614 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=58420', 'data', 'file=/tmp/tmpy_ntexaz/40layo8x.json', 'init=/tmp/tmpy_ntexaz/tggki_pd.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modely6uyqur2/prophet_model-20260323111011.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:11,614.614 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:11,669.669 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:11,752.752 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:11,753.753 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:11,767.767 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:11,770.770 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/fhor4_px.json
[D 2026-03-23 11:10:11,773.773 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/banrn36o.json
[D 2026-03-23 11:10:11,774.774 cmdstanpy] idx 0
[D 2026-03-23 11:10:11,774.774 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:11,774.774 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=79076', 'data', 'file=/tmp/tmpy_ntexaz/fhor4_px.json', 'init=/tmp/tmpy_ntexaz/banrn36o.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model5c17tzvc/prophet_model-20260323111011.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:11,774.774 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:11,967.967 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:12,066.066 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:12,067.067 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:12,085.085 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:12,089.089 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/sa0m2qf5.json
[D 2026-03-23 11:10:12,092.092 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/cdpqb8yd.json
[D 2026-03-23 11:10:12,093.093 cmdstanpy] idx 0
[D 2026-03-23 11:10:12,093.093 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:12,093.093 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=93591', 'data', 'file=/tmp/tmpy_ntexaz/sa0m2qf5.json', 'init=/tmp/tmpy_ntexaz/cdpqb8yd.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model_mv0yxi3/prophet_model-20260323111012.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:12,093.093 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:12,274.274 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:12,360.360 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:12,360.360 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:12,376.376 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:12,379.379 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/9i9hfzix.json
[D 2026-03-23 11:10:12,381.381 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/jecc45gi.json
[D 2026-03-23 11:10:12,382.382 cmdstanpy] idx 0
[D 2026-03-23 11:10:12,382.382 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:12,382.382 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=30244', 'data', 'file=/tmp/tmpy_ntexaz/9i9hfzix.json', 'init=/tmp/tmpy_ntexaz/jecc45gi.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeld1bm3rdx/prophet_model-20260323111012.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:12,382.382 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:12,635.635 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:12,731.731 prophet] Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
[I 2026-03-23 11:10:12,731.731 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:12,731.731 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:12,743.743 prophet] n_changepoints greater than number of observations. Using 12.
[D 2026-03-23 11:10:12,746.746 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/hf2trbnt.json
[D 2026-03-23 11:10:12,746.746 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/c_noqimz.json
[D 2026-03-23 11:10:12,747.747 cmdstanpy] idx 0
[D 2026-03-23 11:10:12,747.747 cmdstanpy] running CmdStan, num_threads: None

{'Account Setup Operations': {'model': <prophet.forecaster.Prophet object at 0x7efa386391d0>, 'forecast':            ds        trend   yhat_lower   yhat_upper  trend_lower  \
31 2026-03-01  1873.359082  2675.304955  2834.773309  1872.375479
32 2026-04-01  1800.256866  2333.970864  2491.737127  1797.240652
33 2026-05-01  1729.512786  2512.650041  2667.923789  1723.803963
34 2026-06-01  1656.410570  2489.427361  2645.595738  1646.515472
35 2026-07-01  1585.666489  2660.392726  2821.882036  1571.720382
36 2026-08-01  1512.564273  1876.589547  2044.813214  1494.223426
37 2026-09-01  1439.462057  2496.925161  2670.236742  1416.607758
38 2026-10-01  1368.717976  2629.485984  2800.286277  1341.240342
39 2026-11-01  1295.615760  2474.714682  2645.892338  1262.190313
40 2026-12-01  1224.871680  1703.414878  1882.773298  1184.812484
41 2027-01-01  1151.769464  2027.027992  2218.533464  1104.713358
42 2027-02-01  1078.667247  1900.847264  2100.782590  1024.961190

    trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  \
31  1874.265050      879.482892            879.482892            879.482892
32  1803.232965      612.711946            612.711946            612.711946
33  1735.216020      855.034682            855.034682            855.034682
34  1665.409701      910.097850            910.097850            910.097850
35  1598.589621     1151.869601           1151.869601           1151.869601
36  1529.851572      454.683400            454.683400            454.683400
37  1462.153413     1144.927067           1144.927067           1144.927067
38  1396.454046     1348.055477           1348.055477           1348.055477
39  1328.550559     1267.507591           1267.507591           1267.507591
40  1262.684662      571.654852            571.654852            571.654852
41  1195.401239      973.815466            973.815466            973.815466
42  1128.161528      925.189725            925.189725            925.189725

    extra_regressors_additive  ...  unique_accounts  unique_accounts_lower  \
31                 748.514948  ...       748.514948             748.514948
32                 782.148544  ...       782.148544             782.148544
33                 815.606890  ...       815.606890             815.606890
34                 848.889814  ...       848.889814             848.889814
35                 881.997168  ...       881.997168             881.997168
36                 914.928823  ...       914.928823             914.928823
37                 947.684672  ...       947.684672             947.684672
38                 980.264631  ...       980.264631             980.264631
39                1012.668632  ...      1012.668632            1012.668632
40                1044.896632  ...      1044.896632            1044.896632
41                1076.948605  ...      1076.948605            1076.948605
42                1108.824545  ...      1108.824545            1108.824545

    unique_accounts_upper      yearly  yearly_lower  yearly_upper  \
31             748.514948  130.967944    130.967944    130.967944
32             782.148544 -169.436598   -169.436598   -169.436598
33             815.606890   39.427792     39.427792     39.427792
34             848.889814   61.208036     61.208036     61.208036
35             881.997168  269.872433    269.872433    269.872433
36             914.928823 -460.245423   -460.245423   -460.245423
37             947.684672  197.242394    197.242394    197.242394
38             980.264631  367.790846    367.790846    367.790846
39            1012.668632  254.838959    254.838959    254.838959
40            1044.896632 -473.241780   -473.241780   -473.241780
41            1076.948605 -103.133139   -103.133139   -103.133139
42            1108.824545 -183.634820   -183.634820   -183.634820

    multiplicative_terms  multiplicative_terms_lower  \
31                   0.0                         0.0
32                   0.0                         0.0
33                   0.0                         0.0
34                   0.0                         0.0
35                   0.0                         0.0
36                   0.0                         0.0
37                   0.0                         0.0
38                   0.0                         0.0
39                   0.0                         0.0
40                   0.0                         0.0
41                   0.0                         0.0
42                   0.0                         0.0

    multiplicative_terms_upper         yhat
31                         0.0  2752.841975
32                         0.0  2412.968812
33                         0.0  2584.547468
34                         0.0  2566.508420
35                         0.0  2737.536090
36                         0.0  1967.247673
37                         0.0  2584.389123
38                         0.0  2716.773453
39                         0.0  2563.123351
40                         0.0  1796.526532
41                         0.0  2125.584930
42                         0.0  2003.856973

[12 rows x 22 columns], 'r_squared': None, 'mape': nan}, 'China': {'model': <prophet.forecaster.Prophet object at 0x7efb71e8ea90>, 'forecast':            ds      trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
29 2026-03-01  35.842781   54.860549   68.736051    35.842780    35.842781
30 2026-04-01  36.588524   39.711427   54.022795    36.588524    36.588525
31 2026-05-01  37.310212    5.393977   20.016146    37.310212    37.310212
32 2026-06-01  38.055956   30.954879   45.040289    38.055956    38.055956
33 2026-07-01  38.777644   41.491182   55.423608    38.777644    38.777644
34 2026-08-01  39.523388   33.439785   48.040563    39.523388    39.523388
35 2026-09-01  40.269132   66.651077   80.569782    40.269132    40.269132
36 2026-10-01  40.990820   23.289468   37.442389    40.990819    40.990820
37 2026-11-01  41.736564   24.528962   38.067752    41.736563    41.736564
38 2026-12-01  42.458251   27.680311   41.779200    42.458251    42.458252
39 2027-01-01  43.203995   28.507579   42.936748    43.203995    43.203996
40 2027-02-01  43.949739   21.352286   34.843869    43.949739    43.949740

    additive_terms  additive_terms_lower  additive_terms_upper  \
29       26.294693             26.294693             26.294693
30       10.365973             10.365973             10.365973
31      -24.485107            -24.485107            -24.485107
32        0.107386              0.107386              0.107386
33       10.014159             10.014159             10.014159
34        1.422063              1.422063              1.422063
35       33.150077             33.150077             33.150077
36      -10.583499            -10.583499            -10.583499
37      -10.316083            -10.316083            -10.316083
38       -7.576144             -7.576144             -7.576144
39       -7.743003             -7.743003             -7.743003
40      -15.692465            -15.692465            -15.692465

    extra_regressors_additive  ...  unique_accounts  unique_accounts_lower  \
29                  -1.793284  ...        -1.793284              -1.793284
30                  -1.879445  ...        -1.879445              -1.879445
31                  -1.965156  ...        -1.965156              -1.965156
32                  -2.050418  ...        -2.050418              -2.050418
33                  -2.135230  ...        -2.135230              -2.135230
34                  -2.219592  ...        -2.219592              -2.219592
35                  -2.303503  ...        -2.303503              -2.303503
36                  -2.386964  ...        -2.386964              -2.386964
37                  -2.469975  ...        -2.469975              -2.469975
38                  -2.552534  ...        -2.552534              -2.552534
39                  -2.634643  ...        -2.634643              -2.634643
40                  -2.716300  ...        -2.716300              -2.716300

    unique_accounts_upper     yearly  yearly_lower  yearly_upper  \
29              -1.793284  28.087977     28.087977     28.087977
30              -1.879445  12.245417     12.245417     12.245417
31              -1.965156 -22.519951    -22.519951    -22.519951
32              -2.050418   2.157804      2.157804      2.157804
33              -2.135230  12.149388     12.149388     12.149388
34              -2.219592   3.641654      3.641654      3.641654
35              -2.303503  35.453580     35.453580     35.453580
36              -2.386964  -8.196535     -8.196535     -8.196535
37              -2.469975  -7.846108     -7.846108     -7.846108
38              -2.552534  -5.023609     -5.023609     -5.023609
39              -2.634643  -5.108361     -5.108361     -5.108361
40              -2.716300 -12.976164    -12.976164    -12.976164

    multiplicative_terms  multiplicative_terms_lower  \
29                   0.0                         0.0
30                   0.0                         0.0
31                   0.0                         0.0
32                   0.0                         0.0
33                   0.0                         0.0
34                   0.0                         0.0
35                   0.0                         0.0
36                   0.0                         0.0
37                   0.0                         0.0
38                   0.0                         0.0
39                   0.0                         0.0
40                   0.0                         0.0

    multiplicative_terms_upper       yhat
29                         0.0  62.137473
30                         0.0  46.954497
31                         0.0  12.825105
32                         0.0  38.163342
33                         0.0  48.791802
34                         0.0  40.945451
35                         0.0  73.419209
36                         0.0  30.407321
37                         0.0  31.420481
38                         0.0  34.882108
39                         0.0  35.460992
40                         0.0  28.257275

[12 rows x 22 columns], 'r_squared': None, 'mape': nan}, 'Disputes': {'model': <prophet.forecaster.Prophet object at 0x7efa373aa890>, 'forecast':            ds        trend   yhat_lower   yhat_upper  trend_lower  \
31 2026-03-01  2031.397019  2638.476585  3193.359641  2031.397010
32 2026-04-01  2034.326790  1762.436031  2330.161736  2034.326762
33 2026-05-01  2037.162052  2104.333563  2659.776113  2037.161997
34 2026-06-01  2040.091823  2707.775442  3278.398381  2040.091731
35 2026-07-01  2042.927085  2739.978279  3288.707014  2042.926954
36 2026-08-01  2045.856856  1520.710479  2082.615190  2045.856675
37 2026-09-01  2048.786627  1963.341237  2524.932780  2048.786400
38 2026-10-01  2051.621889  2644.758789  3208.879565  2051.621603
39 2026-11-01  2054.551659  1943.742465  2502.942791  2054.551320
40 2026-12-01  2057.386921  1791.925281  2339.413125  2057.386524
41 2027-01-01  2060.316692  1926.724365  2459.710202  2060.316240
42 2027-02-01  2063.246463  1993.205325  2566.927763  2063.245953

    trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  \
31  2031.397029      876.052217            876.052217            876.052217
32  2034.326821       26.497685             26.497685             26.497685
33  2037.162114      345.827059            345.827059            345.827059
34  2040.091920      949.714784            949.714784            949.714784
35  2042.927227      970.060660            970.060660            970.060660
36  2045.857046     -252.353284           -252.353284           -252.353284
37  2048.786865      192.079831            192.079831            192.079831
38  2051.622174      862.679672            862.679672            862.679672
39  2054.551993      174.344059            174.344059            174.344059
40  2057.387313       15.309955             15.309955             15.309955
41  2060.317139      147.548136            147.548136            147.548136
42  2063.246975      221.205386            221.205386            221.205386

    extra_regressors_additive  ...  unique_accounts  unique_accounts_lower  \
31                 256.777246  ...       256.777246             256.777246
32                 268.315215  ...       268.315215             268.315215
33                 279.793064  ...       279.793064             279.793064
34                 291.210736  ...       291.210736             291.210736
35                 302.568178  ...       302.568178             302.568178
36                 313.865346  ...       313.865346             313.865346
37                 325.102205  ...       325.102205             325.102205
38                 336.278725  ...       336.278725             336.278725
39                 347.394883  ...       347.394883             347.394883
40                 358.450663  ...       358.450663             358.450663
41                 369.446058  ...       369.446058             369.446058
42                 380.381065  ...       380.381065             380.381065

    unique_accounts_upper      yearly  yearly_lower  yearly_upper  \
31             256.777246  619.274971    619.274971    619.274971
32             268.315215 -241.817530   -241.817530   -241.817530
33             279.793064   66.033995     66.033995     66.033995
34             291.210736  658.504048    658.504048    658.504048
35             302.568178  667.492482    667.492482    667.492482
36             313.865346 -566.218631   -566.218631   -566.218631
37             325.102205 -133.022374   -133.022374   -133.022374
38             336.278725  526.400947    526.400947    526.400947
39             347.394883 -173.050823   -173.050823   -173.050823
40             358.450663 -343.140709   -343.140709   -343.140709
41             369.446058 -221.897922   -221.897922   -221.897922
42             380.381065 -159.175679   -159.175679   -159.175679

    multiplicative_terms  multiplicative_terms_lower  \
31                   0.0                         0.0
32                   0.0                         0.0
33                   0.0                         0.0
34                   0.0                         0.0
35                   0.0                         0.0
36                   0.0                         0.0
37                   0.0                         0.0
38                   0.0                         0.0
39                   0.0                         0.0
40                   0.0                         0.0
41                   0.0                         0.0
42                   0.0                         0.0

    multiplicative_terms_upper         yhat
31                         0.0  2907.449236
32                         0.0  2060.824476
33                         0.0  2382.989111
34                         0.0  2989.806607
35                         0.0  3012.987745
36                         0.0  1793.503571
37                         0.0  2240.866458
38                         0.0  2914.301560
39                         0.0  2228.895719
40                         0.0  2072.696876
41                         0.0  2207.864828
42                         0.0  2284.451849

[12 rows x 22 columns], 'r_squared': None, 'mape': nan}, 'Ecom APM': {'model': <prophet.forecaster.Prophet object at 0x7efa374d06d0>, 'forecast':            ds       trend   yhat_lower   yhat_upper  trend_lower  trend_upper  \
31 2026-03-01  734.877067  1245.614616  1375.827974   734.211634   735.635316
32 2026-04-01  718.216103   983.907826  1105.778390   716.049988   720.679323
33 2026-05-01  702.092589   759.835389   887.480792   697.926688   706.558943
34 2026-06-01  685.431625   771.245334   897.609015   678.626090   692.570461
35 2026-07-01  669.308111   810.360381   933.900332   659.654068   679.348553
36 2026-08-01  652.647147  1046.955683  1179.839580   639.773614   665.703509
37 2026-09-01  635.986183   919.638929  1048.904195   619.722862   653.039002
38 2026-10-01  619.862669   929.490583  1057.718833   599.274854   640.746237
39 2026-11-01  603.201705   877.849954  1017.408689   577.995050   627.007399
40 2026-12-01  587.078192   701.242276   839.566089   558.060908   614.959885
41 2027-01-01  570.417227   854.805067   995.642591   537.117048   602.020436
42 2027-02-01  553.756263   808.408149   956.070030   515.262971   590.674660

    additive_terms  additive_terms_lower  additive_terms_upper  \
31      576.121460            576.121460            576.121460
32      324.923037            324.923037            324.923037
33      120.918873            120.918873            120.918873
34      150.772623            150.772623            150.772623
35      203.546335            203.546335            203.546335
36      463.100726            463.100726            463.100726
37      350.263719            350.263719            350.263719
38      370.768156            370.768156            370.768156
39      340.939844            340.939844            340.939844
40      181.353797            181.353797            181.353797
41      354.526904            354.526904            354.526904
42      330.361646            330.361646            330.361646

    extra_regressors_additive  ...  unique_accounts  unique_accounts_lower  \
31                 219.972300  ...       219.972300             219.972300
32                 229.856484  ...       229.856484             229.856484
33                 239.689165  ...       239.689165             239.689165
34                 249.470295  ...       249.470295             249.470295
35                 259.199827  ...       259.199827             259.199827
36                 268.877726  ...       268.877726             268.877726
37                 278.503959  ...       278.503959             278.503959
38                 288.078502  ...       288.078502             288.078502
39                 297.601335  ...       297.601335             297.601335
40                 307.072445  ...       307.072445             307.072445
41                 316.491824  ...       316.491824             316.491824
42                 325.859471  ...       325.859471             325.859471

    unique_accounts_upper      yearly  yearly_lower  yearly_upper  \
31             219.972300  356.149160    356.149160    356.149160
32             229.856484   95.066554     95.066554     95.066554
33             239.689165 -118.770292   -118.770292   -118.770292
34             249.470295  -98.697672    -98.697672    -98.697672
35             259.199827  -55.653492    -55.653492    -55.653492
36             268.877726  194.223000    194.223000    194.223000
37             278.503959   71.759759     71.759759     71.759759
38             288.078502   82.689654     82.689654     82.689654
39             297.601335   43.338509     43.338509     43.338509
40             307.072445 -125.718647   -125.718647   -125.718647
41             316.491824   38.035080     38.035080     38.035080
42             325.859471    4.502175      4.502175      4.502175

    multiplicative_terms  multiplicative_terms_lower  \
31                   0.0                         0.0
32                   0.0                         0.0
33                   0.0                         0.0
34                   0.0                         0.0
35                   0.0                         0.0
36                   0.0                         0.0
37                   0.0                         0.0
38                   0.0                         0.0
39                   0.0                         0.0
40                   0.0                         0.0
41                   0.0                         0.0
42                   0.0                         0.0

    multiplicative_terms_upper         yhat
31                         0.0  1310.998527
32                         0.0  1043.139140
33                         0.0   823.011462
34                         0.0   836.204248
35                         0.0   872.854446

In [73]:
# Get current timestamp
current_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Prepare lists to collect results for each component
forecast_list = []
r_squared_list = []
mape_list = []

# Loop through the results and gather data
for squad, result in results.items():
    # Add forecast data (ds and yhat)
    forecast_df = result['forecast'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()
    forecast_df[['yhat', 'yhat_lower', 'yhat_upper']] = forecast_df[['yhat', 'yhat_lower', 'yhat_upper']].clip(lower=0)
    forecast_df['squad'] = squad  # Add the squad name for identification
    forecast_df['timestamp'] = current_timestamp  # Add timestamp
    forecast_df['category'] = 'Service'  # Add category column
    forecast_list.append(forecast_df)
    
    # Add R-squared data
    r_squared_list.append({'squad': squad, 'r_squared': result['r_squared'], 'timestamp': current_timestamp})
    
    # Add MAPE data
    mape_list.append({'squad': squad, 'mape': result['mape'], 'timestamp': current_timestamp})

# Combine the lists into DataFrames
forecast_combined = pd.concat(forecast_list, ignore_index=True)
r_squared_combined = pd.DataFrame(r_squared_list)
mape_combined = pd.DataFrame(mape_list)

# Ensure correct column names
forecast_combined.columns = ['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'squad', 'timestamp', 'category']

# Save the combined data to CSV files
forecast_combined.to_csv('service_combined_forecast.csv', mode='w', header=True, index=False)
r_squared_combined.to_csv('service_combined_r_squared.csv', mode='w', header=True, index=False)
mape_combined.to_csv('service_combined_mape.csv', mode='w', header=True, index=False)

print(f"All results have been saved to service_combined_forecast.csv, service_combined_r_squared.csv, and service_combined_mape.csv with timestamp {current_timestamp}.")

All results have been saved to service_combined_forecast.csv, service_combined_r_squared.csv, and service_combined_mape.csv with timestamp 2026-03-23 11:10:13.

In [74]:
!hdfs dfs -put -f service_combined_forecast.csv /user/{username}/notebooks/Workload\ Projections/Forecasted\ data

In [75]:
!hdfs dfs -put -f service_combined_forecast.csv /user/{username}/notebooks/adyen_downloader

In [76]:
combined_forecast_df = pd.read_csv('service_combined_forecast.csv')
print("Column names in service_combined_forecast.csv:")
print(combined_forecast_df.columns)

Column names in service_combined_forecast.csv:
Index(['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'squad', 'timestamp',
       'category'],
      dtype='object')

### Internal cases

In [77]:
def create_internal_cases_df(df):

    df['month'] = pd.to_datetime(df['month'])

    filtered_df = df[
        (df['month'].dt.date < current_month_start) &
        (df['month'].dt.date >= pd.to_datetime('2023-09-01').date()) &
        (~df['origin'].isin(['Side Conversation', 'Call'])) &
        (df['category'] == 'Internal')
    ]

    service_df = (
        filtered_df
        .groupby(['month', 'support_team'], as_index=False)
        .agg(cases=('unique_id_count', 'sum'))
        .dropna()
    )

    internal_df = service_df.rename(columns={
        'month': 'month',
        'support_team': 'squad',
        'cases': 'cases'
    })

    return internal_df

In [78]:
internal_df = create_internal_cases_df(tickets)
print(internal_df)

         month                        squad  cases
0   2023-09-01     Account Setup Operations   1915
1   2023-09-01                        China      5
2   2023-09-01                     Disputes   1171
3   2023-09-01                     Ecom APM    106
4   2023-09-01                   Ecom Cards     67
..         ...                          ...    ...
500 2026-02-01  LATAM - Operational Support    105
501 2026-02-01    LATAM - Technical Support     73
502 2026-02-01          Operational Support    569
503 2026-02-01              Partner Support     71
504 2026-02-01                    Platforms     45

[505 rows x 3 columns]

In [79]:
def prepare_forecast_df(internal_df):
    df = (
        internal_df
        .rename(columns={'month': 'ds', 'cases': 'y'})
        .dropna(subset=['ds', 'y'])
    )
    return df

In [80]:
test = prepare_forecast_df(internal_df)
print(test)

            ds                        squad     y
0   2023-09-01     Account Setup Operations  1915
1   2023-09-01                        China     5
2   2023-09-01                     Disputes  1171
3   2023-09-01                     Ecom APM   106
4   2023-09-01                   Ecom Cards    67
..         ...                          ...   ...
500 2026-02-01  LATAM - Operational Support   105
501 2026-02-01    LATAM - Technical Support    73
502 2026-02-01          Operational Support   569
503 2026-02-01              Partner Support    71
504 2026-02-01                    Platforms    45

[505 rows x 3 columns]

In [81]:
nested_df = {
    squad: df.drop(columns='squad')
    for squad, df in test.groupby('squad')
}
print(nested_df)

{'Account Setup Operations':             ds     y
0   2023-09-01  1915
15  2023-10-01  2447
30  2023-11-01  2294
44  2023-12-01  2385
59  2024-01-01  3484
74  2024-02-01  3468
90  2024-03-01  2070
105 2024-04-01  2928
121 2024-05-01  2539
137 2024-06-01  2635
153 2024-07-01  3164
169 2024-08-01  3406
186 2024-09-01  2850
202 2024-10-01  3525
220 2024-11-01  2652
238 2024-12-01  2559
255 2025-01-01  2426
273 2025-02-01  2434
291 2025-03-01  2431
309 2025-04-01  2776
327 2025-05-01  2359
344 2025-06-01  2536
361 2025-07-01  2459
379 2025-08-01  1497
397 2025-09-01  1491
415 2025-10-01  1625
433 2025-11-01  1335
451 2025-12-01  1200
469 2026-01-01  1127
487 2026-02-01  1285, 'China':             ds   y
1   2023-09-01   5
16  2023-10-01   1
45  2023-12-01   1
60  2024-01-01   1
75  2024-02-01   2
106 2024-04-01  43
122 2024-05-01  14
138 2024-06-01  31
154 2024-07-01  22
170 2024-08-01  31
187 2024-09-01  23
203 2024-10-01  15
221 2024-11-01  38
239 2024-12-01  12
256 2025-01-01   8
274 2025-02-01  12
292 2025-03-01   8
310 2025-04-01  12
328 2025-05-01   4
345 2025-06-01   7
362 2025-07-01   7
380 2025-08-01   7
398 2025-09-01   7
416 2025-10-01   3
434 2025-11-01  10
452 2025-12-01  13
470 2026-01-01  12
488 2026-02-01   7, 'Disputes':             ds     y
2   2023-09-01  1171
17  2023-10-01  1035
31  2023-11-01   488
46  2023-12-01   924
61  2024-01-01   780
76  2024-02-01   671
91  2024-03-01  1276
107 2024-04-01  1117
123 2024-05-01   887
139 2024-06-01   889
155 2024-07-01   685
171 2024-08-01   629
188 2024-09-01   550
204 2024-10-01   409
222 2024-11-01   244
240 2024-12-01   269
257 2025-01-01   293
275 2025-02-01   270
293 2025-03-01   326
311 2025-04-01   285
329 2025-05-01   353
346 2025-06-01   319
363 2025-07-01   352
381 2025-08-01   323
399 2025-09-01   436
417 2025-10-01   405
435 2025-11-01   361
453 2025-12-01   410
471 2026-01-01   413
489 2026-02-01   554, 'Ecom APM':             ds    y
3   2023-09-01  106
18  2023-10-01   77
32  2023-11-01   93
47  2023-12-01   96
62  2024-01-01  123
77  2024-02-01  205
92  2024-03-01  142
108 2024-04-01  240
124 2024-05-01  291
140 2024-06-01  204
156 2024-07-01  329
172 2024-08-01  239
189 2024-09-01  226
205 2024-10-01  222
223 2024-11-01  318
241 2024-12-01  252
258 2025-01-01  193
276 2025-02-01  205
294 2025-03-01  269
312 2025-04-01  293
330 2025-05-01  311
347 2025-06-01  240
364 2025-07-01  196
382 2025-08-01  194
400 2025-09-01  160
418 2025-10-01  178
436 2025-11-01  159
454 2025-12-01  146
472 2026-01-01  181
490 2026-02-01  195, 'Ecom Cards':             ds    y
4   2023-09-01   67
19  2023-10-01   83
33  2023-11-01   97
48  2023-12-01  104
63  2024-01-01  143
78  2024-02-01  206
93  2024-03-01  205
109 2024-04-01  169
125 2024-05-01  180
141 2024-06-01  153
157 2024-07-01  214
173 2024-08-01  168
190 2024-09-01  180
206 2024-10-01  237
224 2024-11-01  251
242 2024-12-01  159
259 2025-01-01  194
277 2025-02-01  244
295 2025-03-01  322
313 2025-04-01  277
331 2025-05-01  268
348 2025-06-01  285
365 2025-07-01  259
383 2025-08-01  189
401 2025-09-01  178
419 2025-10-01  163
437 2025-11-01  151
455 2025-12-01  153
473 2026-01-01  226
491 2026-02-01  183, 'Ecom Core':             ds    y
5   2023-09-01  172
20  2023-10-01  155
34  2023-11-01  171
49  2023-12-01  155
64  2024-01-01  199
79  2024-02-01  177
94  2024-03-01  226
110 2024-04-01  238
126 2024-05-01  215
142 2024-06-01  174
158 2024-07-01  192
174 2024-08-01  202
191 2024-09-01  169
207 2024-10-01  191
225 2024-11-01  189
243 2024-12-01   98
260 2025-01-01  138
278 2025-02-01  113
296 2025-03-01  139
314 2025-04-01  121
332 2025-05-01  150
349 2025-06-01  160
366 2025-07-01  142
384 2025-08-01  104
402 2025-09-01  115
420 2025-10-01   98
438 2025-11-01   81
456 2025-12-01   76
474 2026-01-01  103
492 2026-02-01   90, 'Ecom Integration':             ds    y
6   2023-09-01   66
21  2023-10-01   49
35  2023-11-01   50
50  2023-12-01   75
65  2024-01-01   85
80  2024-02-01  107
95  2024-03-01  128
111 2024-04-01  140
127 2024-05-01  205
143 2024-06-01  123
159 2024-07-01  140
175 2024-08-01  110
192 2024-09-01  125
208 2024-10-01  121
226 2024-11-01  123
244 2024-12-01   96
261 2025-01-01   88
279 2025-02-01  136
297 2025-03-01  129
315 2025-04-01  148
333 2025-05-01   87
350 2025-06-01  112
367 2025-07-01  108
385 2025-08-01   79
403 2025-09-01  116
421 2025-10-01   68
439 2025-11-01   56
457 2025-12-01   68
475 2026-01-01   59
493 2026-02-01   62, 'Finance':             ds    y
7   2023-09-01   93
22  2023-10-01  147
36  2023-11-01  211
51  2023-12-01  280
66  2024-01-01  398
81  2024-02-01  279
96  2024-03-01  340
112 2024-04-01  341
128 2024-05-01  382
144 2024-06-01  295
160 2024-07-01  356
176 2024-08-01  245
193 2024-09-01  294
209 2024-10-01  323
227 2024-11-01  266
245 2024-12-01  258
262 2025-01-01  396
280 2025-02-01  278
298 2025-03-01  375
316 2025-04-01  331
334 2025-05-01  311
351 2025-06-01  305
368 2025-07-01  397
386 2025-08-01  274
404 2025-09-01  269
422 2025-10-01  211
440 2025-11-01  196
458 2025-12-01  229
476 2026-01-01  155
494 2026-02-01  192, 'IPP Adv. Payments':             ds    y
8   2023-09-01   43
23  2023-10-01   57
37  2023-11-01   51
52  2023-12-01  121
67  2024-01-01   67
82  2024-02-01   74
97  2024-03-01   97
113 2024-04-01   95
129 2024-05-01   80
145 2024-06-01   87
161 2024-07-01  116
177 2024-08-01   77
194 2024-09-01   99
210 2024-10-01  123
228 2024-11-01  102
246 2024-12-01   72
263 2025-01-01   55
281 2025-02-01   89
299 2025-03-01  130
317 2025-04-01  123
335 2025-05-01   86
352 2025-06-01  106
369 2025-07-01  106
387 2025-08-01   85
405 2025-09-01   95
423 2025-10-01   98
441 2025-11-01   62
459 2025-12-01   39
477 2026-01-01   59
495 2026-02-01   64, 'IPP Core':             ds    y
9   2023-09-01   76
24  2023-10-01   75
38  2023-11-01   77
53  2023-12-01   69
68  2024-01-01   85
83  2024-02-01  118
98  2024-03-01   99
114 2024-04-01  135
130 2024-05-01  123
146 2024-06-01  107
162 2024-07-01  152
178 2024-08-01  137
195 2024-09-01  184
211 2024-10-01  167
229 2024-11-01  116
247 2024-12-01   83
264 2025-01-01  116
282 2025-02-01  124
300 2025-03-01  132
318 2025-04-01  160
336 2025-05-01  130
353 2025-06-01  136
370 2025-07-01  138
388 2025-08-01   81
406 2025-09-01   94
424 2025-10-01   89
442 2025-11-01  104
460 2025-12-01   59
478 2026-01-01  108
496 2026-02-01   71, 'IPP Integrations':             ds    y
10  2023-09-01   38
25  2023-10-01   42
39  2023-11-01   34
54  2023-12-01   30
69  2024-01-01   46
84  2024-02-01   68
99  2024-03-01  136
115 2024-04-01   53
131 2024-05-01   52
147 2024-06-01   50
163 2024-07-01   72
179 2024-08-01   57
196 2024-09-01   54
212 2024-10-01   74
230 2024-11-01   48
248 2024-12-01   53
265 2025-01-01   89
283 2025-02-01   66
301 2025-03-01   60
319 2025-04-01   72
337 2025-05-01   97
354 2025-06-01   77
371 2025-07-01   96
389 2025-08-01   72
407 2025-09-01   85
425 2025-10-01   67
443 2025-11-01   77
461 2025-12-01   55
479 2026-01-01   45
497 2026-02-01   48, 'India - Technical Support':             ds   y
180 2024-08-01  21
197 2024-09-01  11
213 2024-10-01  27
231 2024-11-01  68
249 2024-12-01  33
266 2025-01-01  28
284 2025-02-01  25
302 2025-03-01  31
320 2025-04-01  11
338 2025-05-01   2
355 2025-06-01  19
372 2025-07-01   6
390 2025-08-01  30
408 2025-09-01  10
426 2025-10-01  22
444 2025-11-01  26
462 2025-12-01  17
480 2026-01-01  12
498 2026-02-01  17, 'Japan':             ds   y
85  2024-02-01   1
100 2024-03-01   1
116 2024-04-01   8
132 2024-05-01   5
148 2024-06-01   2
164 2024-07-01   3
181 2024-08-01   4
214 2024-10-01   3
232 2024-11-01   1
267 2025-01-01   2
285 2025-02-01   3
303 2025-03-01   3
321 2025-04-01   1
373 2025-07-01   1
391 2025-08-01   2
409 2025-09-01  15
427 2025-10-01  15
445 2025-11-01  20
463 2025-12-01  15
481 2026-01-01  17
499 2026-02-01   3, 'LATAM - Operational Support':             ds    y
11  2023-09-01  238
26  2023-10-01  253
40  2023-11-01  238
55  2023-12-01  289
70  2024-01-01  820
86  2024-02-01  497
101 2024-03-01  708
117 2024-04-01  539
133 2024-05-01  492
149 2024-06-01  514
165 2024-07-01  598
182 2024-08-01  418
198 2024-09-01  395
215 2024-10-01  301
233 2024-11-01  246
250 2024-12-01  292
268 2025-01-01  276
286 2025-02-01  278
304 2025-03-01  275
322 2025-04-01  398
339 2025-05-01  300
356 2025-06-01  326
374 2025-07-01  324
392 2025-08-01  292
410 2025-09-01  307
428 2025-10-01  164
446 2025-11-01  168
464 2025-12-01  217
482 2026-01-01  125
500 2026-02-01  105, 'LATAM - Technical Support':             ds    y
12  2023-09-01  141
27  2023-10-01   99
41  2023-11-01  153
56  2023-12-01   90
71  2024-01-01  133
87  2024-02-01   73
102 2024-03-01   86
118 2024-04-01  104
134 2024-05-01  160
150 2024-06-01  131
166 2024-07-01  153
183 2024-08-01  166
199 2024-09-01  128
216 2024-10-01  158
234 2024-11-01  162
251 2024-12-01  144
269 2025-01-01  158
287 2025-02-01  169
305 2025-03-01  187
323 2025-04-01  120
340 2025-05-01  170
357 2025-06-01  101
375 2025-07-01  162
393 2025-08-01  132
411 2025-09-01  143
429 2025-10-01  137
447 2025-11-01  215
465 2025-12-01  178
483 2026-01-01  133
501 2026-02-01   73, 'Operational Support':             ds     y
13  2023-09-01  1739
28  2023-10-01  1208
42  2023-11-01  1797
57  2023-12-01  2471
72  2024-01-01  3401
88  2024-02-01  3237
103 2024-03-01  2662
119 2024-04-01  3389
135 2024-05-01  2320
151 2024-06-01  1851
167 2024-07-01  1766
184 2024-08-01  1008
200 2024-09-01  1029
217 2024-10-01   909
235 2024-11-01   902
252 2024-12-01   919
270 2025-01-01  1024
288 2025-02-01   889
306 2025-03-01  1063
324 2025-04-01  1027
341 2025-05-01   986
358 2025-06-01  1041
376 2025-07-01  1003
394 2025-08-01   644
412 2025-09-01   745
430 2025-10-01   711
448 2025-11-01   542
466 2025-12-01   705
484 2026-01-01   658
502 2026-02-01   569, 'Partner Support':             ds    y
218 2024-10-01    1
236 2024-11-01   24
253 2024-12-01   58
271 2025-01-01   71
289 2025-02-01  126
307 2025-03-01   71
325 2025-04-01   77
342 2025-05-01   80
359 2025-06-01  108
377 2025-07-01   96
395 2025-08-01   84
413 2025-09-01   54
431 2025-10-01   42
449 2025-11-01   53
467 2025-12-01   47
485 2026-01-01   29
503 2026-02-01   71, 'Platforms':             ds    y
14  2023-09-01  154
29  2023-10-01  106
43  2023-11-01   85
58  2023-12-01  103
73  2024-01-01  146
89  2024-02-01  205
104 2024-03-01   74
120 2024-04-01   58
136 2024-05-01   70
152 2024-06-01   49
168 2024-07-01   65
185 2024-08-01   40
201 2024-09-01   37
219 2024-10-01   63
237 2024-11-01   67
254 2024-12-01   54
272 2025-01-01   65
290 2025-02-01   81
308 2025-03-01   58
326 2025-04-01   51
343 2025-05-01   72
360 2025-06-01   64
378 2025-07-01   72
396 2025-08-01   80
414 2025-09-01   69
432 2025-10-01   69
450 2025-11-01   58
468 2025-12-01   43
486 2026-01-01   40
504 2026-02-01   45}

In [82]:
def run_internal_prophet(df):
    
     # Ensure required columns are present
    required_cols = {'ds', 'y'}
    if not required_cols.issubset(df.columns):
        return None
    
    # Remove NAs and check row count
    df = df.dropna(subset=['ds', 'y'])
    if len(df) < 10:
        return None  # Prophet requires enough data points
    
    # Fit the model with regressor
    m = Prophet()
    m.fit(df)
    
    # Make future df
    future = m.make_future_dataframe(periods=13, freq='M')
    future['ds'] = future['ds'].values.astype('datetime64[M]')
    
    # Forecast
    forecast = m.predict(future)
    last_train_date = df['ds'].max()
    forecast = forecast[forecast['ds'] > last_train_date]
    
    # Model evaluation on historical part
    comparison = df.merge(forecast[['ds', 'yhat']], on='ds', how='left').dropna()
    comparison['residuals'] = comparison['y'] - comparison['yhat']

    ss_res = np.sum(comparison['residuals'] ** 2)
    ss_tot = np.sum((comparison['y'] - np.mean(comparison['y'])) ** 2)
    r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else None

    mape = np.mean(np.abs((comparison['y'] - comparison['yhat']) / comparison['y'])) * 100

    return {
        'model': m,
        'forecast': forecast,
        'r_squared': r_squared,
        'mape': mape
    }

In [83]:
results = {}
for squad, df in nested_df.items():
    result = run_internal_prophet(df)
    if result is not None:
        results[squad] = result
print(results)

[I 2026-03-23 11:10:21,521.521 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:21,521.521 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:21,535.535 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:21,537.537 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/hyana4wt.json
[D 2026-03-23 11:10:21,539.539 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/_b22w3sv.json
[D 2026-03-23 11:10:21,540.540 cmdstanpy] idx 0
[D 2026-03-23 11:10:21,540.540 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:21,540.540 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=75192', 'data', 'file=/tmp/tmpy_ntexaz/hyana4wt.json', 'init=/tmp/tmpy_ntexaz/_b22w3sv.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modela2w151p0/prophet_model-20260323111021.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:21,540.540 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:21,767.767 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:21,844.844 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:21,844.844 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:21,856.856 prophet] n_changepoints greater than number of observations. Using 21.
[D 2026-03-23 11:10:21,859.859 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/kw0xhedf.json
[D 2026-03-23 11:10:21,866.866 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/8obnsh4x.json
[D 2026-03-23 11:10:21,867.867 cmdstanpy] idx 0
[D 2026-03-23 11:10:21,867.867 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:21,867.867 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=98030', 'data', 'file=/tmp/tmpy_ntexaz/kw0xhedf.json', 'init=/tmp/tmpy_ntexaz/8obnsh4x.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelqn29v22u/prophet_model-20260323111021.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:21,867.867 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:21,986.986 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:22,061.061 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:22,061.061 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:22,075.075 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:22,078.078 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/w7m0ypnb.json
[D 2026-03-23 11:10:22,081.081 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/wj8jcdf4.json
[D 2026-03-23 11:10:22,083.083 cmdstanpy] idx 0
[D 2026-03-23 11:10:22,083.083 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:22,083.083 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=5150', 'data', 'file=/tmp/tmpy_ntexaz/w7m0ypnb.json', 'init=/tmp/tmpy_ntexaz/wj8jcdf4.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model1go_t126/prophet_model-20260323111022.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:22,083.083 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:22,244.244 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:22,314.314 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:22,314.314 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:22,327.327 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:22,329.329 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/gfft426z.json
[D 2026-03-23 11:10:22,332.332 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/p3xocdmq.json
[D 2026-03-23 11:10:22,333.333 cmdstanpy] idx 0
[D 2026-03-23 11:10:22,333.333 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:22,333.333 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=3447', 'data', 'file=/tmp/tmpy_ntexaz/gfft426z.json', 'init=/tmp/tmpy_ntexaz/p3xocdmq.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_model0rkfs69q/prophet_model-20260323111022.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:22,333.333 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:22,514.514 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:22,827.827 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:22,827.827 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:22,840.840 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:22,843.843 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/jyz49531.json
[D 2026-03-23 11:10:22,845.845 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/tsi0myc9.json
[D 2026-03-23 11:10:22,846.846 cmdstanpy] idx 0
[D 2026-03-23 11:10:22,846.846 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:22,846.846 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=1030', 'data', 'file=/tmp/tmpy_ntexaz/jyz49531.json', 'init=/tmp/tmpy_ntexaz/tsi0myc9.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelmtwl8_mx/prophet_model-20260323111022.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:22,846.846 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:23,048.048 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:23,131.131 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:23,131.131 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:23,144.144 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:23,147.147 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/x2z4kg13.json
[D 2026-03-23 11:10:23,151.151 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/22kd4rbi.json
[D 2026-03-23 11:10:23,151.151 cmdstanpy] idx 0
[D 2026-03-23 11:10:23,152.152 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:23,152.152 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=4002', 'data', 'file=/tmp/tmpy_ntexaz/x2z4kg13.json', 'init=/tmp/tmpy_ntexaz/22kd4rbi.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelssxai_mq/prophet_model-20260323111023.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:23,152.152 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:23,361.361 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:23,435.435 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:23,435.435 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:23,447.447 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:23,450.450 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/oxewsy2g.json
[D 2026-03-23 11:10:23,453.453 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/rbj_fkzr.json
[D 2026-03-23 11:10:23,454.454 cmdstanpy] idx 0
[D 2026-03-23 11:10:23,454.454 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:23,454.454 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=55705', 'data', 'file=/tmp/tmpy_ntexaz/oxewsy2g.json', 'init=/tmp/tmpy_ntexaz/rbj_fkzr.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelgba6qpw2/prophet_model-20260323111023.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:23,454.454 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:23,600.600 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:23,678.678 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:23,678.678 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:23,690.690 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:23,693.693 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/o3ehatny.json
[D 2026-03-23 11:10:23,695.695 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/1tgds2eh.json
[D 2026-03-23 11:10:23,696.696 cmdstanpy] idx 0
[D 2026-03-23 11:10:23,696.696 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:23,696.696 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=72331', 'data', 'file=/tmp/tmpy_ntexaz/o3ehatny.json', 'init=/tmp/tmpy_ntexaz/1tgds2eh.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeltfys6hqg/prophet_model-20260323111023.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:23,697.697 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:23,880.880 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:23,952.952 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:23,952.952 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:23,967.967 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:23,970.970 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/duvqs4ax.json
[D 2026-03-23 11:10:23,972.972 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/p9nnffjz.json
[D 2026-03-23 11:10:23,973.973 cmdstanpy] idx 0
[D 2026-03-23 11:10:23,973.973 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:23,973.973 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=91056', 'data', 'file=/tmp/tmpy_ntexaz/duvqs4ax.json', 'init=/tmp/tmpy_ntexaz/p9nnffjz.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelifwkod5g/prophet_model-20260323111023.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:23,973.973 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:24,180.180 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:24,250.250 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:24,251.251 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:24,263.263 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:24,266.266 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/r6e_widg.json
[D 2026-03-23 11:10:24,270.270 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/quclcb0f.json
[D 2026-03-23 11:10:24,271.271 cmdstanpy] idx 0
[D 2026-03-23 11:10:24,271.271 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:24,271.271 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=14956', 'data', 'file=/tmp/tmpy_ntexaz/r6e_widg.json', 'init=/tmp/tmpy_ntexaz/quclcb0f.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelxf0z3yzy/prophet_model-20260323111024.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:24,271.271 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:24,518.518 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:24,584.584 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:24,584.584 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:24,595.595 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:24,598.598 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/kuapa7ng.json
[D 2026-03-23 11:10:24,600.600 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/gd9n1f4l.json
[D 2026-03-23 11:10:24,601.601 cmdstanpy] idx 0
[D 2026-03-23 11:10:24,601.601 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:24,601.601 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=23006', 'data', 'file=/tmp/tmpy_ntexaz/kuapa7ng.json', 'init=/tmp/tmpy_ntexaz/gd9n1f4l.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelc_dexwiz/prophet_model-20260323111024.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:24,601.601 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:24,849.849 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:24,928.928 prophet] Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
[I 2026-03-23 11:10:24,928.928 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:24,928.928 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:24,940.940 prophet] n_changepoints greater than number of observations. Using 14.
[D 2026-03-23 11:10:24,942.942 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/kvl__awd.json
[D 2026-03-23 11:10:24,943.943 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/lg3tl4bp.json
[D 2026-03-23 11:10:24,944.944 cmdstanpy] idx 0
[D 2026-03-23 11:10:24,944.944 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:24,944.944 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=81367', 'data', 'file=/tmp/tmpy_ntexaz/kvl__awd.json', 'init=/tmp/tmpy_ntexaz/lg3tl4bp.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeljkkwqnfk/prophet_model-20260323111024.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:24,944.944 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:24,992.992 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:25,061.061 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:25,061.061 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:25,080.080 prophet] n_changepoints greater than number of observations. Using 15.
[D 2026-03-23 11:10:25,086.086 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/td3vt0kw.json
[D 2026-03-23 11:10:25,089.089 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/312n0a4z.json
[D 2026-03-23 11:10:25,090.090 cmdstanpy] idx 0
[D 2026-03-23 11:10:25,090.090 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:25,090.090 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=66358', 'data', 'file=/tmp/tmpy_ntexaz/td3vt0kw.json', 'init=/tmp/tmpy_ntexaz/312n0a4z.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modeldd8qry3c/prophet_model-20260323111025.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:25,090.090 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:27,722.722 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:27,807.807 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:27,807.807 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:27,819.819 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:27,821.821 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/r_e3o8qk.json
[D 2026-03-23 11:10:27,823.823 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/amdw7_gy.json
[D 2026-03-23 11:10:27,824.824 cmdstanpy] idx 0
[D 2026-03-23 11:10:27,824.824 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:27,824.824 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=52279', 'data', 'file=/tmp/tmpy_ntexaz/r_e3o8qk.json', 'init=/tmp/tmpy_ntexaz/amdw7_gy.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelufe0ymv_/prophet_model-20260323111027.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:27,824.824 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:28,012.012 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:28,084.084 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:28,084.084 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:28,101.101 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:28,104.104 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/6gqr_zkr.json
[D 2026-03-23 11:10:28,106.106 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/6daxa44j.json
[D 2026-03-23 11:10:28,107.107 cmdstanpy] idx 0
[D 2026-03-23 11:10:28,107.107 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:28,107.107 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=5936', 'data', 'file=/tmp/tmpy_ntexaz/6gqr_zkr.json', 'init=/tmp/tmpy_ntexaz/6daxa44j.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelqrcbwl11/prophet_model-20260323111028.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:28,107.107 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:28,246.246 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:28,331.331 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:28,331.331 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:28,343.343 prophet] n_changepoints greater than number of observations. Using 23.
[D 2026-03-23 11:10:28,346.346 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/0xhfblvv.json
[D 2026-03-23 11:10:28,348.348 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/pv2v11ra.json
[D 2026-03-23 11:10:28,349.349 cmdstanpy] idx 0
[D 2026-03-23 11:10:28,349.349 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:28,349.349 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=59320', 'data', 'file=/tmp/tmpy_ntexaz/0xhfblvv.json', 'init=/tmp/tmpy_ntexaz/pv2v11ra.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelkzp3hjgb/prophet_model-20260323111028.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:28,349.349 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:28,542.542 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:28,605.605 prophet] Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
[I 2026-03-23 11:10:28,606.606 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:28,606.606 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[I 2026-03-23 11:10:28,616.616 prophet] n_changepoints greater than number of observations. Using 12.
[D 2026-03-23 11:10:28,618.618 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/blfj6i13.json
[D 2026-03-23 11:10:28,619.619 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/kqmegmkt.json
[D 2026-03-23 11:10:28,619.619 cmdstanpy] idx 0
[D 2026-03-23 11:10:28,619.619 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:28,619.619 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=50690', 'data', 'file=/tmp/tmpy_ntexaz/blfj6i13.json', 'init=/tmp/tmpy_ntexaz/kqmegmkt.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelvy6970pl/prophet_model-20260323111028.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']

{'Account Setup Operations': {'model': <prophet.forecaster.Prophet object at 0x7efa374c9650>, 'forecast':            ds        trend   yhat_lower   yhat_upper  trend_lower  \
31 2026-03-01  1632.401527  1096.548876  2081.839588  1632.400497
32 2026-04-01  1577.351556   536.840134  1529.111341  1577.348244
33 2026-05-01  1524.077391   357.901963  1406.348120  1524.071020
34 2026-06-01  1469.027420  1542.932515  2552.755804  1469.017932
35 2026-07-01  1415.753255  2082.427540  3106.335370  1415.740015
36 2026-08-01  1360.703284  1234.288872  2184.245617  1360.686560
37 2026-09-01  1305.653313   103.950615  1073.827376  1305.631309
38 2026-10-01  1252.379148   551.572455  1609.814805  1252.351823
39 2026-11-01  1197.329177   240.253227  1248.029756  1197.296615
40 2026-12-01  1144.055012   152.022842  1216.319769  1144.017186
41 2027-01-01  1089.005041   733.123537  1759.536929  1088.961690
42 2027-02-01  1033.955070   689.908254  1725.827912  1033.905213

    trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  \
31  1632.402462      -37.502785            -37.502785            -37.502785
32  1577.354462     -554.892645           -554.892645           -554.892645
33  1524.082836     -638.703341           -638.703341           -638.703341
34  1469.035978      573.486934            573.486934            573.486934
35  1415.765464     1174.706814           1174.706814           1174.706814
36  1360.719395      340.118930            340.118930            340.118930
37  1305.673896     -698.413799           -698.413799           -698.413799
38  1252.405195     -190.835741           -190.835741           -190.835741
39  1197.360119     -443.944180           -443.944180           -443.944180
40  1144.091373     -432.191923           -432.191923           -432.191923
41  1089.047996      150.150742            150.150742            150.150742
42  1034.004073      183.229884            183.229884            183.229884

         yearly  yearly_lower  yearly_upper  multiplicative_terms  \
31   -37.502785    -37.502785    -37.502785                   0.0
32  -554.892645   -554.892645   -554.892645                   0.0
33  -638.703341   -638.703341   -638.703341                   0.0
34   573.486934    573.486934    573.486934                   0.0
35  1174.706814   1174.706814   1174.706814                   0.0
36   340.118930    340.118930    340.118930                   0.0
37  -698.413799   -698.413799   -698.413799                   0.0
38  -190.835741   -190.835741   -190.835741                   0.0
39  -443.944180   -443.944180   -443.944180                   0.0
40  -432.191923   -432.191923   -432.191923                   0.0
41   150.150742    150.150742    150.150742                   0.0
42   183.229884    183.229884    183.229884                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper         yhat
31                         0.0                         0.0  1594.898742
32                         0.0                         0.0  1022.458912
33                         0.0                         0.0   885.374050
34                         0.0                         0.0  2042.514354
35                         0.0                         0.0  2590.460069
36                         0.0                         0.0  1700.822214
37                         0.0                         0.0   607.239514
38                         0.0                         0.0  1061.543406
39                         0.0                         0.0   753.384997
40                         0.0                         0.0   711.863089
41                         0.0                         0.0  1239.155783
42                         0.0                         0.0  1217.184954  , 'r_squared': None, 'mape': nan}, 'China': {'model': <prophet.forecaster.Prophet object at 0x7efbe4cbeb90>, 'forecast':            ds     trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
29 2026-03-01 -2.984946   21.552745   38.318173    -2.984946    -2.984946
30 2026-04-01 -3.436109  -23.924456   -5.919721    -3.436109    -3.436109
31 2026-05-01 -3.872719   -6.649512   11.117685    -3.872719    -3.872719
32 2026-06-01 -4.323882   -6.807847   10.512608    -4.323883    -4.323882
33 2026-07-01 -4.760492   11.284657   29.540784    -4.760492    -4.760492
34 2026-08-01 -5.211655   12.120349   28.891160    -5.211656    -5.211655
35 2026-09-01 -5.662819  -10.383764    6.617853    -5.662819    -5.662819
36 2026-10-01 -6.099429  -15.096492    2.001738    -6.099429    -6.099428
37 2026-11-01 -6.550592   12.855709   30.735441    -6.550592    -6.550592
38 2026-12-01 -6.987202  -13.345242    4.000403    -6.987202    -6.987201
39 2027-01-01 -7.438365  -14.557135    2.498357    -7.438365    -7.438364
40 2027-02-01 -7.889528  -16.009662    1.107605    -7.889529    -7.889528

    additive_terms  additive_terms_lower  additive_terms_upper     yearly  \
29       32.571816             32.571816             32.571816  32.571816
30      -11.438170            -11.438170            -11.438170 -11.438170
31        5.978437              5.978437              5.978437   5.978437
32        6.039017              6.039017              6.039017   6.039017
33       24.938301             24.938301             24.938301  24.938301
34       25.105110             25.105110             25.105110  25.105110
35        3.938413              3.938413              3.938413   3.938413
36       -0.337130             -0.337130             -0.337130  -0.337130
37       29.075803             29.075803             29.075803  29.075803
38        2.428593              2.428593              2.428593   2.428593
39        1.279495              1.279495              1.279495   1.279495
40        0.779192              0.779192              0.779192   0.779192

    yearly_lower  yearly_upper  multiplicative_terms  \
29     32.571816     32.571816                   0.0
30    -11.438170    -11.438170                   0.0
31      5.978437      5.978437                   0.0
32      6.039017      6.039017                   0.0
33     24.938301     24.938301                   0.0
34     25.105110     25.105110                   0.0
35      3.938413      3.938413                   0.0
36     -0.337130     -0.337130                   0.0
37     29.075803     29.075803                   0.0
38      2.428593      2.428593                   0.0
39      1.279495      1.279495                   0.0
40      0.779192      0.779192                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper       yhat
29                         0.0                         0.0  29.586870
30                         0.0                         0.0 -14.874280
31                         0.0                         0.0   2.105718
32                         0.0                         0.0   1.715135
33                         0.0                         0.0  20.177808
34                         0.0                         0.0  19.893454
35                         0.0                         0.0  -1.724406
36                         0.0                         0.0  -6.436559
37                         0.0                         0.0  22.525211
38                         0.0                         0.0  -4.558609
39                         0.0                         0.0  -6.158870
40                         0.0                         0.0  -7.110336  , 'r_squared': None, 'mape': nan}, 'Disputes': {'model': <prophet.forecaster.Prophet object at 0x7efb6c91ffd0>, 'forecast':            ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
31 2026-03-01  292.321803 -115.058004  296.105363   292.321559   292.322018
32 2026-04-01  271.608721   94.144892  541.343784   271.607947   271.609415
33 2026-05-01  251.563804  366.590302  806.651684   251.562289   251.565154
34 2026-06-01  230.850722   46.704144  476.579073   230.848207   230.852876
35 2026-07-01  210.805805  -44.665881  394.334741   210.802307   210.808939
36 2026-08-01  190.092723 -461.071332  -24.167055   190.088248   190.097031
37 2026-09-01  169.379642   80.987693  513.265259   169.373947   169.385223
38 2026-10-01  149.334724  -31.251551  381.108402   149.327696   149.341560
39 2026-11-01  128.621643 -380.344702   36.868446   128.613190   128.629911
40 2026-12-01  108.576725 -131.021674  303.074471   108.566934   108.586213
41 2027-01-01   87.863644 -184.566484  253.452362    87.852469    87.874747
42 2027-02-01   67.150562 -174.579471  252.099124    67.137977    67.163260

    additive_terms  additive_terms_lower  additive_terms_upper      yearly  \
31     -192.173741           -192.173741           -192.173741 -192.173741
32       43.688684             43.688684             43.688684   43.688684
33      342.971701            342.971701            342.971701  342.971701
34       35.693894             35.693894             35.693894   35.693894
35      -55.170110            -55.170110            -55.170110  -55.170110
36     -422.714032           -422.714032           -422.714032 -422.714032
37      113.015498            113.015498            113.015498  113.015498
38       21.433621             21.433621             21.433621   21.433621
39     -305.858793           -305.858793           -305.858793 -305.858793
40       -9.215533             -9.215533             -9.215533   -9.215533
41      -45.877377            -45.877377            -45.877377  -45.877377
42      -26.924155            -26.924155            -26.924155  -26.924155

    yearly_lower  yearly_upper  multiplicative_terms  \
31   -192.173741   -192.173741                   0.0
32     43.688684     43.688684                   0.0
33    342.971701    342.971701                   0.0
34     35.693894     35.693894                   0.0
35    -55.170110    -55.170110                   0.0
36   -422.714032   -422.714032                   0.0
37    113.015498    113.015498                   0.0
38     21.433621     21.433621                   0.0
39   -305.858793   -305.858793                   0.0
40     -9.215533     -9.215533                   0.0
41    -45.877377    -45.877377                   0.0
42    -26.924155    -26.924155                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper        yhat
31                         0.0                         0.0  100.148061
32                         0.0                         0.0  315.297406
33                         0.0                         0.0  594.535505
34                         0.0                         0.0  266.544616
35                         0.0                         0.0  155.635695
36                         0.0                         0.0 -232.621309
37                         0.0                         0.0  282.395140
38                         0.0                         0.0  170.768345
39                         0.0                         0.0 -177.237150
40                         0.0                         0.0   99.361193
41                         0.0                         0.0   41.986267
42                         0.0                         0.0   40.226407  , 'r_squared': None, 'mape': nan}, 'Ecom APM': {'model': <prophet.forecaster.Prophet object at 0x7efb6c932450>, 'forecast':            ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
31 2026-03-01  233.281257  276.710218  383.320368   233.281183   233.281332
32 2026-04-01  234.462057  180.916458  285.994951   234.461831   234.462314
33 2026-05-01  235.604766  187.743787  291.161991   235.604341   235.605260
34 2026-06-01  236.785566  218.924169  332.045544   236.784867   236.786318
35 2026-07-01  237.928275  143.356397  253.022315   237.927262   237.929345
36 2026-08-01  239.109074  351.483809  457.409774   239.107735   239.110501
37 2026-09-01  240.289874  139.820085  245.211005   240.288118   240.291603
38 2026-10-01  241.432583  126.699491  237.575903   241.430461   241.434747
39 2026-11-01  242.613383  142.097246  250.615366   242.610901   242.615973
40 2026-12-01  243.756092  128.176594  233.876911   243.753111   243.759100
41 2027-01-01  244.936891  137.605097  240.389363   244.933434   244.940434
42 2027-02-01  246.117691  185.887280  296.187011   246.113837   246.121798

    additive_terms  additive_terms_lower  additive_terms_upper      yearly  \
31       98.712646             98.712646             98.712646   98.712646
32       -4.413326             -4.413326             -4.413326   -4.413326
33        5.306123              5.306123              5.306123    5.306123
34       36.857481             36.857481             36.857481   36.857481
35      -41.731831            -41.731831            -41.731831  -41.731831
36      164.566869            164.566869            164.566869  164.566869
37      -50.375456            -50.375456            -50.375456  -50.375456
38      -61.278136            -61.278136            -61.278136  -61.278136
39      -46.196328            -46.196328            -46.196328  -46.196328
40      -63.225189            -63.225189            -63.225189  -63.225189
41      -54.256151            -54.256151            -54.256151  -54.256151
42       -9.623533             -9.623533             -9.623533   -9.623533

    yearly_lower  yearly_upper  multiplicative_terms  \
31     98.712646     98.712646                   0.0
32     -4.413326     -4.413326                   0.0
33      5.306123      5.306123                   0.0
34     36.857481     36.857481                   0.0
35    -41.731831    -41.731831                   0.0
36    164.566869    164.566869                   0.0
37    -50.375456    -50.375456                   0.0
38    -61.278136    -61.278136                   0.0
39    -46.196328    -46.196328                   0.0
40    -63.225189    -63.225189                   0.0
41    -54.256151    -54.256151                   0.0
42     -9.623533     -9.623533                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper        yhat
31                         0.0                         0.0  331.993903
32                         0.0                         0.0  230.048731
33                         0.0                         0.0  240.910889
34                         0.0                         0.0  273.643047
35                         0.0                         0.0  196.196443
36                         0.0                         0.0  403.675944
37                         0.0                         0.0  189.914418
38                         0.0                         0.0  180.154447
39                         0.0                         0.0  196.417054
40                         0.0                         0.0  180.530903
41                         0.0                         0.0  190.680740
42                         0.0                         0.0  236.494158  , 'r_squared': None, 'mape': nan}, 'Ecom Cards': {'model': <prophet.forecaster.Prophet object at 0x7efb6ca7ead0>, 'forecast':            ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
31 2026-03-01  247.692245  309.180186  398.125148   247.692176   247.692311
32 2026-04-01  250.791994  202.721261  286.852626   250.791791   250.792208
33 2026-05-01  253.791752  172.593296  258.087448   253.791347   253.792185
34 2026-06-01  256.891501  277.094033  364.966530   256.890858   256.892210
35 2026-07-01  259.891259  245.096206  331.070582   259.890331   259.892264
36 2026-08-01  262.991008  243.368206  334.629428   262.989749   262.992357
37 2026-09-01  266.090757  163.475307  248.746408   266.089154   266.092535
38 2026-10-01  269.090515  179.205584  264.388304   269.088463   269.092708
39 2026-11-01  272.190264  186.764703  275.436362   272.187817   272.192860
40 2026-12-01  275.190022  177.010852  261.392741   275.187061   275.193061
41 2027-01-01  278.289771  222.249579  306.363754   278.286355   278.293345
42 2027-02-01  281.389521  244.489555  331.140535   281.385594   281.393522

    additive_terms  additive_terms_lower  additive_terms_upper      yearly  \
31      104.608841            104.608841            104.608841  104.608841
32       -6.712475             -6.712475             -6.712475   -6.712475
33      -38.870191            -38.870191            -38.870191  -38.870191
34       63.341934             63.341934             63.341934   63.341934
35       29.117771             29.117771             29.117771   29.117771
36       24.418976             24.418976             24.418976   24.418976
37      -59.072173            -59.072173            -59.072173  -59.072173
38      -46.931899            -46.931899            -46.931899  -46.931899
39      -43.301078            -43.301078            -43.301078  -43.301078
40      -56.737863            -56.737863            -56.737863  -56.737863
41      -15.608158            -15.608158            -15.608158  -15.608158
42        7.474241              7.474241              7.474241    7.474241

    yearly_lower  yearly_upper  multiplicative_terms  \
31    104.608841    104.608841                   0.0
32     -6.712475     -6.712475                   0.0
33    -38.870191    -38.870191                   0.0
34     63.341934     63.341934                   0.0
35     29.117771     29.117771                   0.0
36     24.418976     24.418976                   0.0
37    -59.072173    -59.072173                   0.0
38    -46.931899    -46.931899                   0.0
39    -43.301078    -43.301078                   0.0
40    -56.737863    -56.737863                   0.0
41    -15.608158    -15.608158                   0.0
42      7.474241      7.474241                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper        yhat
31                         0.0                         0.0  352.301086
32                         0.0                         0.0  244.079519
33                         0.0                         0.0  214.921561
34                         0.0                         0.0  320.233435
35                         0.0                         0.0  289.009030
36                         0.0                         0.0  287.409984
37                         0.0                         0.0  207.018584
38                         0.0                         0.0  222.158616
39                         0.0                         0.0  228.889187
40                         0.0                         0.0  218.452159
41                         0.0                         0.0  262.681613
42                         0.0                         0.0  288.863762  , 'r_squared': None, 'mape': nan}, 'Ecom Core': {'model': <prophet.forecaster.Prophet object at 0x7efb56e90d10>, 'forecast':            ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
31 2026-03-01  104.745720  101.435829  137.596891   104.745361   104.746082
32 2026-04-01  101.015031   21.030811   57.003355   101.013859   101.016233
33 2026-05-01   97.404687   85.786105  123.431172    97.402361    97.407047
34 2026-06-01   93.673998  148.511046  183.754848    93.670399    93.677730
35 2026-07-01   90.063654  108.591826  144.218335    90.058663    90.068813
36 2026-08-01   86.332965   49.111625   86.491934    86.326307    86.339980
37 2026-09-01   82.602276   41.168740   79.309151    82.593963    82.611174
38 2026-10-01   78.991931   30.767061   68.230453    78.981804    79.003351
39 2026-11-01   75.261242   34.483082   72.111288    75.249113    75.274809
40 2026-12-01   71.650898    9.815460   49.346806    71.636339    71.667012
41 2027-01-01   67.920209   50.932487   86.083773    67.903398    67.938941
42 2027-02-01   64.189520   28.629395   66.587562    64.170356    64.210414

    additive_terms  additive_terms_lower  additive_terms_upper     yearly  \
31       15.268191             15.268191             15.268191  15.268191
32      -62.010854            -62.010854            -62.010854 -62.010854
33        7.702131              7.702131              7.702131   7.702131

In [84]:
# Get current timestamp
current_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Prepare lists to collect results for each component
forecast_list = []
r_squared_list = []
mape_list = []

# Loop through the results and gather data
for squad, result in results.items():
    # Add forecast data (ds and yhat)
    forecast_df = result['forecast'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()
    forecast_df[['yhat', 'yhat_lower', 'yhat_upper']] = forecast_df[['yhat', 'yhat_lower', 'yhat_upper']].clip(lower=0)
    forecast_df['squad'] = squad  # Add the squad name for identification
    forecast_df['timestamp'] = current_timestamp  # Add timestamp
    forecast_df['category'] = 'Internal'  # Add category column
    forecast_list.append(forecast_df)
    
    # Add R-squared data
    r_squared_list.append({'squad': squad, 'r_squared': result['r_squared'], 'timestamp': current_timestamp})
    
    # Add MAPE data
    mape_list.append({'squad': squad, 'mape': result['mape'], 'timestamp': current_timestamp})

# Combine the lists into DataFrames
forecast_combined = pd.concat(forecast_list, ignore_index=True)
r_squared_combined = pd.DataFrame(r_squared_list)
mape_combined = pd.DataFrame(mape_list)

# Ensure correct column names
forecast_combined.columns = ['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'squad', 'timestamp', 'category']

# Save the combined data to CSV files
forecast_combined.to_csv('internal_combined_forecast.csv', mode='w', header=True, index=False)
r_squared_combined.to_csv('internal_combined_r_squared.csv', mode='w', header=True, index=False)
mape_combined.to_csv('internal_combined_mape.csv', mode='w', header=True, index=False)

print(f"All results have been saved to internal_combined_forecast.csv, internal_combined_r_squared.csv, and internal_combined_mape.csv with timestamp {current_timestamp}.")

All results have been saved to internal_combined_forecast.csv, internal_combined_r_squared.csv, and internal_combined_mape.csv with timestamp 2026-03-23 11:10:29.

In [85]:
internal_combined_forecast = pd.read_csv('internal_combined_forecast.csv')
print(internal_combined_forecast.columns)

Index(['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'squad', 'timestamp',
       'category'],
      dtype='object')

In [86]:
!hdfs dfs -put -f internal_combined_forecast.csv /user/{username}/notebooks/Workload\ Projections/Forecasted\ data

In [87]:
!hdfs dfs -put -f internal_combined_forecast.csv /user/{username}/notebooks/adyen_downloader

## Calls Forecasting

In [88]:
def prepare_forecast_df(calls, account_growth):
    
    calls['month'] = pd.to_datetime(calls['month'])
    account_growth['month'] = pd.to_datetime(account_growth['month'])
    
    calls = calls[
        (calls['month'].dt.date < current_month_start)
    ]
    
    df = (
        calls
        .merge(account_growth, on='month', how='left')
        .rename(columns={'month': 'ds', 'calls': 'y'})
        .dropna(subset=['ds', 'y', 'unique_accounts'])
    )
    return df

In [89]:
test = prepare_forecast_df(calls, combined_df)
print(test)

            ds         support_team     y  unique_accounts    type
0   2023-01-01                Japan   157           7531.0  Actual
1   2023-01-01                LATAM   100           7531.0  Actual
2   2023-01-01  Operational Support  1137           7531.0  Actual
3   2023-02-01                Japan   167           7570.0  Actual
4   2023-02-01                LATAM   107           7570.0  Actual
..         ...                  ...   ...              ...     ...
109 2026-01-01                LATAM    59           9431.0  Actual
110 2026-01-01  Operational Support  1628           9431.0  Actual
111 2026-02-01                Japan   162           9468.0  Actual
112 2026-02-01                LATAM    65           9468.0  Actual
113 2026-02-01  Operational Support  1799           9468.0  Actual

[114 rows x 5 columns]

In [90]:
nested_df = {
    squad: df.drop(columns='support_team')
    for squad, df in test.groupby('support_team')
}
print(nested_df)

{'Japan':             ds    y  unique_accounts    type
0   2023-01-01  157           7531.0  Actual
3   2023-02-01  167           7570.0  Actual
6   2023-03-01  249           7642.0  Actual
9   2023-04-01  175           7697.0  Actual
12  2023-05-01  130           7726.0  Actual
15  2023-06-01  153           7776.0  Actual
18  2023-07-01  136           7821.0  Actual
21  2023-08-01  136           7866.0  Actual
24  2023-09-01  162           7899.0  Actual
27  2023-10-01  178           7963.0  Actual
30  2023-11-01  172           8044.0  Actual
33  2023-12-01  191           8095.0  Actual
36  2024-01-01  271           8123.0  Actual
39  2024-02-01  257           8157.0  Actual
42  2024-03-01  264           8209.0  Actual
45  2024-04-01  248           8300.0  Actual
48  2024-05-01  216           8389.0  Actual
51  2024-06-01  202           8436.0  Actual
54  2024-07-01  266           8488.0  Actual
57  2024-08-01  231           8503.0  Actual
60  2024-09-01  169           8569.0  Actual
63  2024-10-01  245           8647.0  Actual
66  2024-11-01  271           8711.0  Actual
69  2024-12-01  277           8756.0  Actual
72  2025-01-01  202           8821.0  Actual
75  2025-02-01  221           8865.0  Actual
78  2025-03-01  230           8945.0  Actual
81  2025-04-01  252           8998.0  Actual
84  2025-05-01  241           9050.0  Actual
87  2025-06-01  275           9102.0  Actual
90  2025-07-01  234           9156.0  Actual
93  2025-08-01  233           9186.0  Actual
96  2025-09-01  185           9252.0  Actual
99  2025-10-01  201           9294.0  Actual
102 2025-11-01  190           9359.0  Actual
105 2025-12-01  272           9406.0  Actual
108 2026-01-01  206           9431.0  Actual
111 2026-02-01  162           9468.0  Actual, 'LATAM':             ds    y  unique_accounts    type
1   2023-01-01  100           7531.0  Actual
4   2023-02-01  107           7570.0  Actual
7   2023-03-01   99           7642.0  Actual
10  2023-04-01   89           7697.0  Actual
13  2023-05-01   93           7726.0  Actual
16  2023-06-01   51           7776.0  Actual
19  2023-07-01   81           7821.0  Actual
22  2023-08-01   92           7866.0  Actual
25  2023-09-01  101           7899.0  Actual
28  2023-10-01   65           7963.0  Actual
31  2023-11-01   74           8044.0  Actual
34  2023-12-01   60           8095.0  Actual
37  2024-01-01   53           8123.0  Actual
40  2024-02-01  101           8157.0  Actual
43  2024-03-01   62           8209.0  Actual
46  2024-04-01   93           8300.0  Actual
49  2024-05-01   84           8389.0  Actual
52  2024-06-01   58           8436.0  Actual
55  2024-07-01   75           8488.0  Actual
58  2024-08-01   95           8503.0  Actual
61  2024-09-01   85           8569.0  Actual
64  2024-10-01  113           8647.0  Actual
67  2024-11-01   46           8711.0  Actual
70  2024-12-01   18           8756.0  Actual
73  2025-01-01   42           8821.0  Actual
76  2025-02-01   48           8865.0  Actual
79  2025-03-01   67           8945.0  Actual
82  2025-04-01   91           8998.0  Actual
85  2025-05-01   63           9050.0  Actual
88  2025-06-01   62           9102.0  Actual
91  2025-07-01   39           9156.0  Actual
94  2025-08-01   63           9186.0  Actual
97  2025-09-01   40           9252.0  Actual
100 2025-10-01   85           9294.0  Actual
103 2025-11-01   83           9359.0  Actual
106 2025-12-01   52           9406.0  Actual
109 2026-01-01   59           9431.0  Actual
112 2026-02-01   65           9468.0  Actual, 'Operational Support':             ds     y  unique_accounts    type
2   2023-01-01  1137           7531.0  Actual
5   2023-02-01  1257           7570.0  Actual
8   2023-03-01  1511           7642.0  Actual
11  2023-04-01  1281           7697.0  Actual
14  2023-05-01  1550           7726.0  Actual
17  2023-06-01  1528           7776.0  Actual
20  2023-07-01  1510           7821.0  Actual
23  2023-08-01  1441           7866.0  Actual
26  2023-09-01  2154           7899.0  Actual
29  2023-10-01  2440           7963.0  Actual
32  2023-11-01  2184           8044.0  Actual
35  2023-12-01  1998           8095.0  Actual
38  2024-01-01  2260           8123.0  Actual
41  2024-02-01  2056           8157.0  Actual
44  2024-03-01  2193           8209.0  Actual
47  2024-04-01  2139           8300.0  Actual
50  2024-05-01  2322           8389.0  Actual
53  2024-06-01  2295           8436.0  Actual
56  2024-07-01  2481           8488.0  Actual
59  2024-08-01  2007           8503.0  Actual
62  2024-09-01  1832           8569.0  Actual
65  2024-10-01  2166           8647.0  Actual
68  2024-11-01  1840           8711.0  Actual
71  2024-12-01  1683           8756.0  Actual
74  2025-01-01  2013           8821.0  Actual
77  2025-02-01  1835           8865.0  Actual
80  2025-03-01  2342           8945.0  Actual
83  2025-04-01  2409           8998.0  Actual
86  2025-05-01  2237           9050.0  Actual
89  2025-06-01  2179           9102.0  Actual
92  2025-07-01  2375           9156.0  Actual
95  2025-08-01  1896           9186.0  Actual
98  2025-09-01  2022           9252.0  Actual
101 2025-10-01  1978           9294.0  Actual
104 2025-11-01  1928           9359.0  Actual
107 2025-12-01  1684           9406.0  Actual
110 2026-01-01  1628           9431.0  Actual
113 2026-02-01  1799           9468.0  Actual}

In [91]:
results = {}
for squad, df in nested_df.items():
    result = run_internal_prophet(df)
    if result is not None:
        results[squad] = result
print(results)

[I 2026-03-23 11:10:38,393.393 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:38,394.394 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[D 2026-03-23 11:10:38,413.413 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/8pedyry6.json
[D 2026-03-23 11:10:38,417.417 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/a9449ef5.json
[D 2026-03-23 11:10:38,418.418 cmdstanpy] idx 0
[D 2026-03-23 11:10:38,418.418 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:38,418.418 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=83367', 'data', 'file=/tmp/tmpy_ntexaz/8pedyry6.json', 'init=/tmp/tmpy_ntexaz/a9449ef5.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelpk451_mi/prophet_model-20260323111038.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:38,418.418 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:38,656.656 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:38,737.737 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:38,737.737 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[D 2026-03-23 11:10:38,751.751 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/529u6q8t.json
[D 2026-03-23 11:10:38,754.754 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/3qvuw6xo.json
[D 2026-03-23 11:10:38,755.755 cmdstanpy] idx 0
[D 2026-03-23 11:10:38,755.755 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:38,755.755 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=48223', 'data', 'file=/tmp/tmpy_ntexaz/529u6q8t.json', 'init=/tmp/tmpy_ntexaz/3qvuw6xo.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelpray_a76/prophet_model-20260323111038.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:38,755.755 cmdstanpy] Chain [1] start processing
[I 2026-03-23 11:10:38,941.941 cmdstanpy] Chain [1] done processing
[I 2026-03-23 11:10:39,011.011 prophet] Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
[I 2026-03-23 11:10:39,012.012 prophet] Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[D 2026-03-23 11:10:39,027.027 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/q5o4zn63.json
[D 2026-03-23 11:10:39,030.030 cmdstanpy] input tempfile: /tmp/tmpy_ntexaz/pu96qgnx.json
[D 2026-03-23 11:10:39,031.031 cmdstanpy] idx 0
[D 2026-03-23 11:10:39,031.031 cmdstanpy] running CmdStan, num_threads: None
[D 2026-03-23 11:10:39,031.031 cmdstanpy] CmdStan args: ['/home/bigdata/mypkg/prophet/stan_model/prophet_model.bin', 'random', 'seed=17660', 'data', 'file=/tmp/tmpy_ntexaz/q5o4zn63.json', 'init=/tmp/tmpy_ntexaz/pu96qgnx.json', 'output', 'file=/tmp/tmpy_ntexaz/prophet_modelchbimsdm/prophet_model-20260323111039.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[I 2026-03-23 11:10:39,031.031 cmdstanpy] Chain [1] start processing

{'Japan': {'model': <prophet.forecaster.Prophet object at 0x7efbe257a550>, 'forecast':            ds       trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
39 2026-03-01  261.933988  256.710109  331.216401   261.933596   261.934341
40 2026-04-01  263.824040  227.769335  301.201420   263.822790   263.825169
41 2026-05-01  265.653123  196.866067  272.143524   265.650725   265.655348
42 2026-06-01  267.543175  219.806253  297.333889   267.539438   267.546664
43 2026-07-01  269.372258  211.230071  287.555910   269.366936   269.377049
44 2026-08-01  271.262310  207.001326  283.688857   271.254940   271.268594
45 2026-09-01  273.152362  195.948065  270.328472   273.142937   273.160523
46 2026-10-01  274.981445  218.968834  290.342218   274.969616   274.991587
47 2026-11-01  276.871497  206.406208  282.263676   276.857477   276.883825
48 2026-12-01  278.700580  233.532921  308.671045   278.683629   278.715193
49 2027-01-01  280.590632  236.986291  313.768398   280.570546   280.607725
50 2027-02-01  282.480684  228.155847  304.453844   282.458473   282.499837

    additive_terms  additive_terms_lower  additive_terms_upper     yearly  \
39       31.638458             31.638458             31.638458  31.638458
40       -2.119969             -2.119969             -2.119969  -2.119969
41      -31.413416            -31.413416            -31.413416 -31.413416
42       -7.368159             -7.368159             -7.368159  -7.368159
43      -19.010479            -19.010479            -19.010479 -19.010479
44      -27.482057            -27.482057            -27.482057 -27.482057
45      -39.418295            -39.418295            -39.418295 -39.418295
46      -21.228544            -21.228544            -21.228544 -21.228544
47      -32.334349            -32.334349            -32.334349 -32.334349
48       -5.132838             -5.132838             -5.132838  -5.132838
49       -6.221567             -6.221567             -6.221567  -6.221567
50      -17.663362            -17.663362            -17.663362 -17.663362

    yearly_lower  yearly_upper  multiplicative_terms  \
39     31.638458     31.638458                   0.0
40     -2.119969     -2.119969                   0.0
41    -31.413416    -31.413416                   0.0
42     -7.368159     -7.368159                   0.0
43    -19.010479    -19.010479                   0.0
44    -27.482057    -27.482057                   0.0
45    -39.418295    -39.418295                   0.0
46    -21.228544    -21.228544                   0.0
47    -32.334349    -32.334349                   0.0
48     -5.132838     -5.132838                   0.0
49     -6.221567     -6.221567                   0.0
50    -17.663362    -17.663362                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper        yhat
39                         0.0                         0.0  293.572445
40                         0.0                         0.0  261.704071
41                         0.0                         0.0  234.239707
42                         0.0                         0.0  260.175016
43                         0.0                         0.0  250.361779
44                         0.0                         0.0  243.780253
45                         0.0                         0.0  233.734067
46                         0.0                         0.0  253.752900
47                         0.0                         0.0  244.537148
48                         0.0                         0.0  273.567741
49                         0.0                         0.0  274.369065
50                         0.0                         0.0  264.817322  , 'r_squared': None, 'mape': nan}, 'LATAM': {'model': <prophet.forecaster.Prophet object at 0x7efad8140590>, 'forecast':            ds      trend  yhat_lower  yhat_upper  trend_lower  trend_upper  \
39 2026-03-01  58.294042   40.243082   73.070970    58.294041    58.294042
40 2026-04-01  57.401526   48.604652   79.884772    57.401525    57.401528
41 2026-05-01  56.537802   43.240442   75.862709    56.537800    56.537804
42 2026-06-01  55.645287   16.077093   50.239564    55.645283    55.645290
43 2026-07-01  54.781562   31.727724   62.943637    54.781557    54.781568
44 2026-08-01  53.889047   47.445673   79.699614    53.889040    53.889054
45 2026-09-01  52.996532   44.753131   76.836368    52.996523    52.996541
46 2026-10-01  52.132807   41.162098   71.631447    52.132797    52.132819
47 2026-11-01  51.240292   30.504343   64.690820    51.240279    51.240306
48 2026-12-01  50.376567    8.862507   40.960106    50.376553    50.376584
49 2027-01-01  49.484052   19.465095   52.201542    49.484035    49.484071
50 2027-02-01  48.591537   40.303922   73.806691    48.591518    48.591558

    additive_terms  additive_terms_lower  additive_terms_upper     yearly  \
39       -1.807457             -1.807457             -1.807457  -1.807457
40        6.884528              6.884528              6.884528   6.884528
41        2.875404              2.875404              2.875404   2.875404
42      -22.276791            -22.276791            -22.276791 -22.276791
43       -7.229452             -7.229452             -7.229452  -7.229452
44        9.929798              9.929798              9.929798   9.929798
45        7.618874              7.618874              7.618874   7.618874
46        3.243627              3.243627              3.243627   3.243627
47       -3.301021             -3.301021             -3.301021  -3.301021
48      -25.168568            -25.168568            -25.168568 -25.168568
49      -14.483724            -14.483724            -14.483724 -14.483724
50        8.732205              8.732205              8.732205   8.732205

    yearly_lower  yearly_upper  multiplicative_terms  \
39     -1.807457     -1.807457                   0.0
40      6.884528      6.884528                   0.0
41      2.875404      2.875404                   0.0
42    -22.276791    -22.276791                   0.0
43     -7.229452     -7.229452                   0.0
44      9.929798      9.929798                   0.0
45      7.618874      7.618874                   0.0
46      3.243627      3.243627                   0.0
47     -3.301021     -3.301021                   0.0
48    -25.168568    -25.168568                   0.0
49    -14.483724    -14.483724                   0.0
50      8.732205      8.732205                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper       yhat
39                         0.0                         0.0  56.486585
40                         0.0                         0.0  64.286054
41                         0.0                         0.0  59.413206
42                         0.0                         0.0  33.368495
43                         0.0                         0.0  47.552110
44                         0.0                         0.0  63.818844
45                         0.0                         0.0  60.615406
46                         0.0                         0.0  55.376434
47                         0.0                         0.0  47.939271
48                         0.0                         0.0  25.207999
49                         0.0                         0.0  35.000329
50                         0.0                         0.0  57.323742  , 'r_squared': None, 'mape': nan}, 'Operational Support': {'model': <prophet.forecaster.Prophet object at 0x7efbe256d610>, 'forecast':            ds        trend   yhat_lower   yhat_upper  trend_lower  \
39 2026-03-01  2275.231443  1938.376705  2635.749076  2275.227910
40 2026-04-01  2288.864656  1879.271348  2582.236249  2288.853376
41 2026-05-01  2302.058087  2050.186283  2733.993270  2302.036454
42 2026-06-01  2315.691300  2020.248316  2713.172050  2315.657464
43 2026-07-01  2328.884731  2014.997962  2734.187880  2328.835724
44 2026-08-01  2342.517943  1678.527249  2401.484773  2342.453261
45 2026-09-01  2356.151156  2039.763577  2754.652996  2356.068045
46 2026-10-01  2369.344587  2158.818598  2900.847393  2369.244154
47 2026-11-01  2382.977800  1940.695516  2623.596396  2382.859034
48 2026-12-01  2396.171231  1721.170583  2448.331837  2396.031482
49 2027-01-01  2409.804443  1800.204657  2526.946917  2409.643076
50 2027-02-01  2423.437656  1801.049223  2546.248835  2423.249437

    trend_upper  additive_terms  additive_terms_lower  additive_terms_upper  \
39  2275.235214       17.140537             17.140537             17.140537
40  2288.876710      -49.874465            -49.874465            -49.874465
41  2302.081782       99.961727             99.961727             99.961727
42  2315.729082       44.322140             44.322140             44.322140
43  2328.938165       54.293325             54.293325             54.293325
44  2342.586956     -282.989829           -282.989829           -282.989829
45  2356.238342       42.302170             42.302170             42.302170
46  2369.451549      161.981458            161.981458            161.981458
47  2383.103477      -98.394679            -98.394679            -98.394679
48  2396.321518     -309.936343           -309.936343           -309.936343
49  2409.978266     -255.139295           -255.139295           -255.139295
50  2423.635358     -242.633835           -242.633835           -242.633835

        yearly  yearly_lower  yearly_upper  multiplicative_terms  \
39   17.140537     17.140537     17.140537                   0.0
40  -49.874465    -49.874465    -49.874465                   0.0
41   99.961727     99.961727     99.961727                   0.0
42   44.322140     44.322140     44.322140                   0.0
43   54.293325     54.293325     54.293325                   0.0
44 -282.989829   -282.989829   -282.989829                   0.0
45   42.302170     42.302170     42.302170                   0.0
46  161.981458    161.981458    161.981458                   0.0
47  -98.394679    -98.394679    -98.394679                   0.0
48 -309.936343   -309.936343   -309.936343                   0.0
49 -255.139295   -255.139295   -255.139295                   0.0
50 -242.633835   -242.633835   -242.633835                   0.0

    multiplicative_terms_lower  multiplicative_terms_upper         yhat
39                         0.0                         0.0  2292.371981
40                         0.0                         0.0  2238.990191
41                         0.0                         0.0  2402.019814
42                         0.0                         0.0  2360.013440
43                         0.0                         0.0  2383.178056
44                         0.0                         0.0  2059.528114
45                         0.0                         0.0  2398.453326
46                         0.0                         0.0  2531.326046
47                         0.0                         0.0  2284.583121
48                         0.0                         0.0  2086.234888
49                         0.0                         0.0  2154.665148
50                         0.0                         0.0  2180.803821  , 'r_squared': None, 'mape': nan}}

[I 2026-03-23 11:10:39,255.255 cmdstanpy] Chain [1] done processing

In [92]:
# Get current timestamp
current_timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Prepare lists to collect results for each component
forecast_list = []
r_squared_list = []
mape_list = []

# Loop through the results and gather data
for squad, result in results.items():
    # Add forecast data (ds and yhat)
    forecast_df = result['forecast'][['ds', 'yhat', 'yhat_lower', 'yhat_upper']].copy()
    forecast_df[['yhat', 'yhat_lower', 'yhat_upper']] = forecast_df[['yhat', 'yhat_lower', 'yhat_upper']].clip(lower=0)
    forecast_df['squad'] = squad  # Add the squad name for identification
    forecast_df['timestamp'] = current_timestamp  # Add timestamp
    forecast_df['category'] = 'Calls'  # Add category column
    forecast_list.append(forecast_df)
    
    # Add R-squared data
    r_squared_list.append({'squad': squad, 'r_squared': result['r_squared'], 'timestamp': current_timestamp})
    
    # Add MAPE data
    mape_list.append({'squad': squad, 'mape': result['mape'], 'timestamp': current_timestamp})

# Combine the lists into DataFrames
forecast_combined = pd.concat(forecast_list, ignore_index=True)
r_squared_combined = pd.DataFrame(r_squared_list)
mape_combined = pd.DataFrame(mape_list)

# Ensure correct column names
forecast_combined.columns = ['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'squad', 'timestamp', 'category']

# Save the combined data to CSV files
forecast_combined.to_csv('calls_forecast.csv', mode='w', header=True, index=False)
r_squared_combined.to_csv('calls_r_squared.csv', mode='w', header=True, index=False)
mape_combined.to_csv('calls_mape.csv', mode='w', header=True, index=False)

print(f"All results have been saved to calls_forecast.csv, calls_r_squared.csv, and calls_mape.csv with timestamp {current_timestamp}.")

All results have been saved to calls_forecast.csv, calls_r_squared.csv, and calls_mape.csv with timestamp 2026-03-23 11:10:39.

In [93]:
!hdfs dfs -put -f calls_forecast.csv /user/{username}/notebooks/Workload\ Projections/Forecasted\ data

In [94]:
!hdfs dfs -put -f calls_forecast.csv /user/{username}/notebooks/adyen_downloader

## Copy to streams

In [5]:
!hdfs dfs -ls /streams/technical_excellence/support

NOTE: Picked up JDK_JAVA_OPTIONS:     --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED    --add-opens=java.base/java.io=ALL-UNNAMED     --add-opens=java.base/java.lang=ALL-UNNAMED     --add-opens=java.base/java.lang.reflect=ALL-UNNAMED     --add-opens=java.base/java.math=ALL-UNNAMED     --add-opens=java.base/java.net=ALL-UNNAMED     --add-opens=java.base/java.text=ALL-UNNAMED     --add-opens=java.base/java.util=ALL-UNNAMED     --add-opens=java.base/java.util.concurrent=ALL-UNNAMED     --add-opens=java.base/java.util.zip=ALL-UNNAMED     --add-opens=java.base/sun.security.util=ALL-UNNAMED     --add-opens=java.base/sun.security.x509=ALL-UNNAMED
Found 1 items
drwxr-xr-x   - catarinap hdfs          0 2026-05-07 10:59 /streams/technical_excellence/support/Workload Projections

In [96]:
# !hdfs dfs -rm -r /streams/technical_excellence/support/Workload\ Projections

In [97]:
# !hdfs dfs -cp /user/{username}/notebooks/Workload\ Projections /streams/technical_excellence/support

In [4]:
!hdfs dfs -cp -f /user/{username}/notebooks/Workload\ Projections /streams/technical_excellence/support

NOTE: Picked up JDK_JAVA_OPTIONS:     --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED    --add-opens=java.base/java.io=ALL-UNNAMED     --add-opens=java.base/java.lang=ALL-UNNAMED     --add-opens=java.base/java.lang.reflect=ALL-UNNAMED     --add-opens=java.base/java.math=ALL-UNNAMED     --add-opens=java.base/java.net=ALL-UNNAMED     --add-opens=java.base/java.text=ALL-UNNAMED     --add-opens=java.base/java.util=ALL-UNNAMED     --add-opens=java.base/java.util.concurrent=ALL-UNNAMED     --add-opens=java.base/java.util.zip=ALL-UNNAMED     --add-opens=java.base/sun.security.util=ALL-UNNAMED     --add-opens=java.base/sun.security.x509=ALL-UNNAMED